// Code generated by epostix-codegen. DO NOT EDIT.

package epostix

import (
	"context"
	"net/url"
	"time"
)

var _ = time.Time{}
var _ = url.Values{}

type AnalyticsResource struct {
	client *Client
}

type GetAnalyticsSummaryParams struct {
	Start   time.Time
	End     time.Time
	Purpose *GetAnalyticsSummaryPurpose
}

func (p *GetAnalyticsSummaryParams) values() url.Values {
	out := url.Values{}
	if p == nil {
		return out
	}

	out.Set("start", formatQueryValue(p.Start))
	out.Set("end", formatQueryValue(p.End))
	if p.Purpose != nil {
		out.Set("purpose", formatQueryValue(*p.Purpose))
	}

	return out
}

type GetAnalyticsTimeseriesParams struct {
	Start    time.Time
	End      time.Time
	Interval *GetAnalyticsTimeseriesInterval
	Purpose  *GetAnalyticsTimeseriesPurpose
}

func (p *GetAnalyticsTimeseriesParams) values() url.Values {
	out := url.Values{}
	if p == nil {
		return out
	}

	out.Set("start", formatQueryValue(p.Start))
	out.Set("end", formatQueryValue(p.End))
	if p.Interval != nil {
		out.Set("interval", formatQueryValue(*p.Interval))
	}
	if p.Purpose != nil {
		out.Set("purpose", formatQueryValue(*p.Purpose))
	}

	return out
}

func (r *AnalyticsResource) GetAnalyticsSummary(ctx context.Context, params *GetAnalyticsSummaryParams, opts ...RequestOption) (*AnalyticsSummary, error) {
	req := &requestInput{
		op:    operations.GetAnalyticsSummary,
		query: params.values(),
	}

	return execute[AnalyticsSummary](ctx, r.client, req, opts...)
}

func (r *AnalyticsResource) GetAnalyticsTimeseries(ctx context.Context, params *GetAnalyticsTimeseriesParams, opts ...RequestOption) (*AnalyticsTimeseries, error) {
	req := &requestInput{
		op:    operations.GetAnalyticsTimeseries,
		query: params.values(),
	}

	return execute[AnalyticsTimeseries](ctx, r.client, req, opts...)
}
