// Code generated by epostix-codegen. DO NOT EDIT.

package epostix

import (
	"context"
	"net/url"
	"time"
)

var _ = time.Time{}
var _ = url.Values{}

type APIKeysResource struct {
	client *Client
}

type GetAPIKeyUsageParams struct {
	Limit         *int
	StartingAfter *string
	EndingBefore  *string
}

func (p *GetAPIKeyUsageParams) values() url.Values {
	out := url.Values{}
	if p == nil {
		return out
	}

	if p.Limit != nil {
		out.Set("limit", formatQueryValue(*p.Limit))
	}
	if p.StartingAfter != nil {
		out.Set("starting_after", formatQueryValue(*p.StartingAfter))
	}
	if p.EndingBefore != nil {
		out.Set("ending_before", formatQueryValue(*p.EndingBefore))
	}

	return out
}

type ListAPIKeysParams struct {
	Limit         *int
	StartingAfter *string
	EndingBefore  *string
}

func (p *ListAPIKeysParams) values() url.Values {
	out := url.Values{}
	if p == nil {
		return out
	}

	if p.Limit != nil {
		out.Set("limit", formatQueryValue(*p.Limit))
	}
	if p.StartingAfter != nil {
		out.Set("starting_after", formatQueryValue(*p.StartingAfter))
	}
	if p.EndingBefore != nil {
		out.Set("ending_before", formatQueryValue(*p.EndingBefore))
	}

	return out
}

func (r *APIKeysResource) CreateAPIKey(ctx context.Context, body *APIKeyCreateRequest, opts ...RequestOption) (*APIKeyCreateResponse, error) {
	req := &requestInput{
		op:   operations.CreateAPIKey,
		body: body,
	}

	return execute[APIKeyCreateResponse](ctx, r.client, req, opts...)
}

func (r *APIKeysResource) DeleteAPIKey(ctx context.Context, aPIKeyID string, opts ...RequestOption) error {
	req := &requestInput{
		op:   operations.DeleteAPIKey,
		path: []string{aPIKeyID},
	}

	_, err := execute[struct{}](ctx, r.client, req, opts...)
	return err
}

func (r *APIKeysResource) GetAPIKey(ctx context.Context, aPIKeyID string, opts ...RequestOption) (*APIKeyResponse, error) {
	req := &requestInput{
		op:   operations.GetAPIKey,
		path: []string{aPIKeyID},
	}

	return execute[APIKeyResponse](ctx, r.client, req, opts...)
}

func (r *APIKeysResource) GetAPIKeyUsage(ctx context.Context, aPIKeyID string, params *GetAPIKeyUsageParams, opts ...RequestOption) (*APIKeyUsageListResponse, error) {
	req := &requestInput{
		op:    operations.GetAPIKeyUsage,
		path:  []string{aPIKeyID},
		query: params.values(),
	}

	return execute[APIKeyUsageListResponse](ctx, r.client, req, opts...)
}

func (r *APIKeysResource) GetAPIKeyUsageIterator(ctx context.Context, aPIKeyID string, params *GetAPIKeyUsageParams, opts ...RequestOption) *Iterator[APIKeyUsageLog] {
	return newIterator[APIKeyUsageLog](ctx, r.client, &paginateInput{
		op:          operations.GetAPIKeyUsage,
		path:        []string{aPIKeyID},
		query:       params.values(),
		cursorParam: "starting_after",
	}, opts...)
}

func (r *APIKeysResource) ListAPIKeys(ctx context.Context, params *ListAPIKeysParams, opts ...RequestOption) (*APIKeyListResponse, error) {
	req := &requestInput{
		op:    operations.ListAPIKeys,
		query: params.values(),
	}

	return execute[APIKeyListResponse](ctx, r.client, req, opts...)
}

func (r *APIKeysResource) ListAPIKeysIterator(ctx context.Context, params *ListAPIKeysParams, opts ...RequestOption) *Iterator[APIKeyResponse] {
	return newIterator[APIKeyResponse](ctx, r.client, &paginateInput{
		op:          operations.ListAPIKeys,
		query:       params.values(),
		cursorParam: "starting_after",
	}, opts...)
}

func (r *APIKeysResource) UpdateAPIKey(ctx context.Context, aPIKeyID string, body *APIKeyUpdateRequest, opts ...RequestOption) (*APIKeyResponse, error) {
	req := &requestInput{
		op:   operations.UpdateAPIKey,
		path: []string{aPIKeyID},
		body: body,
	}

	return execute[APIKeyResponse](ctx, r.client, req, opts...)
}
