// Code generated by epostix-codegen. DO NOT EDIT.

package epostix

import (
	"context"
	"net/url"
	"time"
)

var _ = time.Time{}
var _ = url.Values{}

type BroadcastsResource struct {
	client *Client
}

type ListBroadcastsParams struct {
	Limit         *int
	StartingAfter *string
	Status        *BroadcastStatus
}

func (p *ListBroadcastsParams) values() url.Values {
	out := url.Values{}
	if p == nil {
		return out
	}

	if p.Limit != nil {
		out.Set("limit", formatQueryValue(*p.Limit))
	}
	if p.StartingAfter != nil {
		out.Set("starting_after", formatQueryValue(*p.StartingAfter))
	}
	if p.Status != nil {
		out.Set("status", formatQueryValue(*p.Status))
	}

	return out
}

func (r *BroadcastsResource) CancelBroadcast(ctx context.Context, broadcastID string, opts ...RequestOption) (*Broadcast, error) {
	req := &requestInput{
		op:   operations.CancelBroadcast,
		path: []string{broadcastID},
	}

	return execute[Broadcast](ctx, r.client, req, opts...)
}

func (r *BroadcastsResource) CreateBroadcast(ctx context.Context, body *BroadcastCreate, opts ...RequestOption) (*Broadcast, error) {
	req := &requestInput{
		op:   operations.CreateBroadcast,
		body: body,
	}

	return execute[Broadcast](ctx, r.client, req, opts...)
}

func (r *BroadcastsResource) DeleteBroadcast(ctx context.Context, broadcastID string, opts ...RequestOption) error {
	req := &requestInput{
		op:   operations.DeleteBroadcast,
		path: []string{broadcastID},
	}

	_, err := execute[struct{}](ctx, r.client, req, opts...)
	return err
}

func (r *BroadcastsResource) GetBroadcast(ctx context.Context, broadcastID string, opts ...RequestOption) (*Broadcast, error) {
	req := &requestInput{
		op:   operations.GetBroadcast,
		path: []string{broadcastID},
	}

	return execute[Broadcast](ctx, r.client, req, opts...)
}

func (r *BroadcastsResource) ListBroadcasts(ctx context.Context, params *ListBroadcastsParams, opts ...RequestOption) (*BroadcastListResponse, error) {
	req := &requestInput{
		op:    operations.ListBroadcasts,
		query: params.values(),
	}

	return execute[BroadcastListResponse](ctx, r.client, req, opts...)
}

func (r *BroadcastsResource) ListBroadcastsIterator(ctx context.Context, params *ListBroadcastsParams, opts ...RequestOption) *Iterator[Broadcast] {
	return newIterator[Broadcast](ctx, r.client, &paginateInput{
		op:          operations.ListBroadcasts,
		query:       params.values(),
		cursorParam: "starting_after",
	}, opts...)
}

func (r *BroadcastsResource) SendBroadcast(ctx context.Context, broadcastID string, opts ...RequestOption) (*Broadcast, error) {
	req := &requestInput{
		op:   operations.SendBroadcast,
		path: []string{broadcastID},
	}

	return execute[Broadcast](ctx, r.client, req, opts...)
}

func (r *BroadcastsResource) SendBroadcastTest(ctx context.Context, broadcastID string, body *BroadcastTestRequest, opts ...RequestOption) (*BroadcastTestResult, error) {
	req := &requestInput{
		op:   operations.SendBroadcastTest,
		path: []string{broadcastID},
		body: body,
	}

	return execute[BroadcastTestResult](ctx, r.client, req, opts...)
}

func (r *BroadcastsResource) UpdateBroadcast(ctx context.Context, broadcastID string, body *BroadcastUpdate, opts ...RequestOption) (*Broadcast, error) {
	req := &requestInput{
		op:   operations.UpdateBroadcast,
		path: []string{broadcastID},
		body: body,
	}

	return execute[Broadcast](ctx, r.client, req, opts...)
}
