// Code generated by epostix-codegen. DO NOT EDIT.

package epostix

import (
	"context"
	"net/url"
	"time"
)

var _ = time.Time{}
var _ = url.Values{}

type ContactsResource struct {
	client *Client
}

type ListContactsParams struct {
	Limit          *int
	StartingAfter  *string
	EndingBefore   *string
	Email          *string
	Status         *ListContactsStatus
	EngagementTier *ListContactsEngagementTier
	TagID          *string
	CreatedAfter   *time.Time
	CreatedBefore  *time.Time
}

func (p *ListContactsParams) values() url.Values {
	out := url.Values{}
	if p == nil {
		return out
	}

	if p.Limit != nil {
		out.Set("limit", formatQueryValue(*p.Limit))
	}
	if p.StartingAfter != nil {
		out.Set("starting_after", formatQueryValue(*p.StartingAfter))
	}
	if p.EndingBefore != nil {
		out.Set("ending_before", formatQueryValue(*p.EndingBefore))
	}
	if p.Email != nil {
		out.Set("email", formatQueryValue(*p.Email))
	}
	if p.Status != nil {
		out.Set("status", formatQueryValue(*p.Status))
	}
	if p.EngagementTier != nil {
		out.Set("engagement_tier", formatQueryValue(*p.EngagementTier))
	}
	if p.TagID != nil {
		out.Set("tag_id", formatQueryValue(*p.TagID))
	}
	if p.CreatedAfter != nil {
		out.Set("created_after", formatQueryValue(*p.CreatedAfter))
	}
	if p.CreatedBefore != nil {
		out.Set("created_before", formatQueryValue(*p.CreatedBefore))
	}

	return out
}

func (r *ContactsResource) AssignContactTag(ctx context.Context, contactID string, tagID string, opts ...RequestOption) error {
	req := &requestInput{
		op:   operations.AssignContactTag,
		path: []string{contactID, tagID},
	}

	_, err := execute[struct{}](ctx, r.client, req, opts...)
	return err
}

func (r *ContactsResource) BulkCreateContacts(ctx context.Context, body *BulkContactCreateRequest, opts ...RequestOption) (*BulkContactCreateResponse, error) {
	req := &requestInput{
		op:   operations.BulkCreateContacts,
		body: body,
	}

	return execute[BulkContactCreateResponse](ctx, r.client, req, opts...)
}

func (r *ContactsResource) CreateContact(ctx context.Context, body *ContactCreate, opts ...RequestOption) (*Contact, error) {
	req := &requestInput{
		op:   operations.CreateContact,
		body: body,
	}

	return execute[Contact](ctx, r.client, req, opts...)
}

func (r *ContactsResource) DeleteContact(ctx context.Context, contactID string, opts ...RequestOption) error {
	req := &requestInput{
		op:   operations.DeleteContact,
		path: []string{contactID},
	}

	_, err := execute[struct{}](ctx, r.client, req, opts...)
	return err
}

func (r *ContactsResource) GetContact(ctx context.Context, contactID string, opts ...RequestOption) (*Contact, error) {
	req := &requestInput{
		op:   operations.GetContact,
		path: []string{contactID},
	}

	return execute[Contact](ctx, r.client, req, opts...)
}

func (r *ContactsResource) ListContacts(ctx context.Context, params *ListContactsParams, opts ...RequestOption) (*ContactListResponse, error) {
	req := &requestInput{
		op:    operations.ListContacts,
		query: params.values(),
	}

	return execute[ContactListResponse](ctx, r.client, req, opts...)
}

func (r *ContactsResource) ListContactsIterator(ctx context.Context, params *ListContactsParams, opts ...RequestOption) *Iterator[Contact] {
	return newIterator[Contact](ctx, r.client, &paginateInput{
		op:          operations.ListContacts,
		query:       params.values(),
		cursorParam: "starting_after",
	}, opts...)
}

func (r *ContactsResource) RemoveContactTag(ctx context.Context, contactID string, tagID string, opts ...RequestOption) error {
	req := &requestInput{
		op:   operations.RemoveContactTag,
		path: []string{contactID, tagID},
	}

	_, err := execute[struct{}](ctx, r.client, req, opts...)
	return err
}

func (r *ContactsResource) UnsubscribeContact(ctx context.Context, contactID string, body *UnsubscribeContactBodyObject, opts ...RequestOption) (*Contact, error) {
	req := &requestInput{
		op:   operations.UnsubscribeContact,
		path: []string{contactID},
		body: body,
	}

	return execute[Contact](ctx, r.client, req, opts...)
}

func (r *ContactsResource) UpdateContact(ctx context.Context, contactID string, body *ContactUpdate, opts ...RequestOption) (*Contact, error) {
	req := &requestInput{
		op:   operations.UpdateContact,
		path: []string{contactID},
		body: body,
	}

	return execute[Contact](ctx, r.client, req, opts...)
}

func (r *ContactsResource) UpsertContact(ctx context.Context, email string, body *ContactUpsert, opts ...RequestOption) (*Contact, error) {
	req := &requestInput{
		op:   operations.UpsertContact,
		path: []string{email},
		body: body,
	}

	return execute[Contact](ctx, r.client, req, opts...)
}
