// Code generated by epostix-codegen. DO NOT EDIT.

package epostix

import (
	"context"
	"net/url"
	"time"
)

var _ = time.Time{}
var _ = url.Values{}

type DomainsResource struct {
	client *Client
}

type ListDomainsParams struct {
	Limit         *int
	StartingAfter *string
	EndingBefore  *string
	Status        *ListDomainsStatus
}

func (p *ListDomainsParams) values() url.Values {
	out := url.Values{}
	if p == nil {
		return out
	}

	if p.Limit != nil {
		out.Set("limit", formatQueryValue(*p.Limit))
	}
	if p.StartingAfter != nil {
		out.Set("starting_after", formatQueryValue(*p.StartingAfter))
	}
	if p.EndingBefore != nil {
		out.Set("ending_before", formatQueryValue(*p.EndingBefore))
	}
	if p.Status != nil {
		out.Set("status", formatQueryValue(*p.Status))
	}

	return out
}

func (r *DomainsResource) CreateDomain(ctx context.Context, body *DomainCreateRequest, opts ...RequestOption) (*Domain, error) {
	req := &requestInput{
		op:   operations.CreateDomain,
		body: body,
	}

	return execute[Domain](ctx, r.client, req, opts...)
}

func (r *DomainsResource) DeleteDomain(ctx context.Context, domainID string, opts ...RequestOption) error {
	req := &requestInput{
		op:   operations.DeleteDomain,
		path: []string{domainID},
	}

	_, err := execute[struct{}](ctx, r.client, req, opts...)
	return err
}

func (r *DomainsResource) GetDomain(ctx context.Context, domainID string, opts ...RequestOption) (*Domain, error) {
	req := &requestInput{
		op:   operations.GetDomain,
		path: []string{domainID},
	}

	return execute[Domain](ctx, r.client, req, opts...)
}

func (r *DomainsResource) ListDomains(ctx context.Context, params *ListDomainsParams, opts ...RequestOption) (*DomainListResponse, error) {
	req := &requestInput{
		op:    operations.ListDomains,
		query: params.values(),
	}

	return execute[DomainListResponse](ctx, r.client, req, opts...)
}

func (r *DomainsResource) ListDomainsIterator(ctx context.Context, params *ListDomainsParams, opts ...RequestOption) *Iterator[Domain] {
	return newIterator[Domain](ctx, r.client, &paginateInput{
		op:          operations.ListDomains,
		query:       params.values(),
		cursorParam: "starting_after",
	}, opts...)
}

func (r *DomainsResource) UpdateDomain(ctx context.Context, domainID string, body *DomainUpdate, opts ...RequestOption) (*Domain, error) {
	req := &requestInput{
		op:   operations.UpdateDomain,
		path: []string{domainID},
		body: body,
	}

	return execute[Domain](ctx, r.client, req, opts...)
}

func (r *DomainsResource) VerifyDomain(ctx context.Context, domainID string, opts ...RequestOption) (*Domain, error) {
	req := &requestInput{
		op:   operations.VerifyDomain,
		path: []string{domainID},
	}

	return execute[Domain](ctx, r.client, req, opts...)
}
