// Code generated by epostix-codegen. DO NOT EDIT.

package epostix

import (
	"context"
	"net/url"
	"time"
)

var _ = time.Time{}
var _ = url.Values{}

type EmailsResource struct {
	client *Client
}

type ListEmailEventsParams struct {
	Limit         *int
	StartingAfter *string
	EndingBefore  *string
}

func (p *ListEmailEventsParams) values() url.Values {
	out := url.Values{}
	if p == nil {
		return out
	}

	if p.Limit != nil {
		out.Set("limit", formatQueryValue(*p.Limit))
	}
	if p.StartingAfter != nil {
		out.Set("starting_after", formatQueryValue(*p.StartingAfter))
	}
	if p.EndingBefore != nil {
		out.Set("ending_before", formatQueryValue(*p.EndingBefore))
	}

	return out
}

type ListEmailsParams struct {
	Limit         *int
	StartingAfter *string
	EndingBefore  *string
	Status        *ListEmailsStatus
	To            *string
	From          *string
	Subject       *string
	Tags          []string
	CreatedAfter  *time.Time
	CreatedBefore *time.Time
	DomainID      *string
}

func (p *ListEmailsParams) values() url.Values {
	out := url.Values{}
	if p == nil {
		return out
	}

	if p.Limit != nil {
		out.Set("limit", formatQueryValue(*p.Limit))
	}
	if p.StartingAfter != nil {
		out.Set("starting_after", formatQueryValue(*p.StartingAfter))
	}
	if p.EndingBefore != nil {
		out.Set("ending_before", formatQueryValue(*p.EndingBefore))
	}
	if p.Status != nil {
		out.Set("status", formatQueryValue(*p.Status))
	}
	if p.To != nil {
		out.Set("to", formatQueryValue(*p.To))
	}
	if p.From != nil {
		out.Set("from", formatQueryValue(*p.From))
	}
	if p.Subject != nil {
		out.Set("subject", formatQueryValue(*p.Subject))
	}
	for _, item := range p.Tags {
		out.Add("tags", formatQueryValue(item))
	}
	if p.CreatedAfter != nil {
		out.Set("created_after", formatQueryValue(*p.CreatedAfter))
	}
	if p.CreatedBefore != nil {
		out.Set("created_before", formatQueryValue(*p.CreatedBefore))
	}
	if p.DomainID != nil {
		out.Set("domain_id", formatQueryValue(*p.DomainID))
	}

	return out
}

func (r *EmailsResource) CancelEmail(ctx context.Context, emailID string, opts ...RequestOption) (*CancelEmailResponse, error) {
	req := &requestInput{
		op:   operations.CancelEmail,
		path: []string{emailID},
	}

	return execute[CancelEmailResponse](ctx, r.client, req, opts...)
}

func (r *EmailsResource) CheckEmail(ctx context.Context, body *EmailCreate, opts ...RequestOption) (*SpamCheckResult, error) {
	req := &requestInput{
		op:   operations.CheckEmail,
		body: body,
	}

	return execute[SpamCheckResult](ctx, r.client, req, opts...)
}

func (r *EmailsResource) GetEmail(ctx context.Context, emailID string, opts ...RequestOption) (*Email, error) {
	req := &requestInput{
		op:   operations.GetEmail,
		path: []string{emailID},
	}

	return execute[Email](ctx, r.client, req, opts...)
}

func (r *EmailsResource) ListEmailEvents(ctx context.Context, emailID string, params *ListEmailEventsParams, opts ...RequestOption) (*EventListResponse, error) {
	req := &requestInput{
		op:    operations.ListEmailEvents,
		path:  []string{emailID},
		query: params.values(),
	}

	return execute[EventListResponse](ctx, r.client, req, opts...)
}

func (r *EmailsResource) ListEmailEventsIterator(ctx context.Context, emailID string, params *ListEmailEventsParams, opts ...RequestOption) *Iterator[Event] {
	return newIterator[Event](ctx, r.client, &paginateInput{
		op:          operations.ListEmailEvents,
		path:        []string{emailID},
		query:       params.values(),
		cursorParam: "starting_after",
	}, opts...)
}

func (r *EmailsResource) ListEmails(ctx context.Context, params *ListEmailsParams, opts ...RequestOption) (*EmailListResponse, error) {
	req := &requestInput{
		op:    operations.ListEmails,
		query: params.values(),
	}

	return execute[EmailListResponse](ctx, r.client, req, opts...)
}

func (r *EmailsResource) ListEmailsIterator(ctx context.Context, params *ListEmailsParams, opts ...RequestOption) *Iterator[Email] {
	return newIterator[Email](ctx, r.client, &paginateInput{
		op:          operations.ListEmails,
		query:       params.values(),
		cursorParam: "starting_after",
	}, opts...)
}

func (r *EmailsResource) ResendEmail(ctx context.Context, emailID string, opts ...RequestOption) (*Email, error) {
	req := &requestInput{
		op:   operations.ResendEmail,
		path: []string{emailID},
	}

	return execute[Email](ctx, r.client, req, opts...)
}

func (r *EmailsResource) SendEmail(ctx context.Context, body *EmailCreate, opts ...RequestOption) (*Email, error) {
	req := &requestInput{
		op:   operations.SendEmail,
		body: body,
	}

	return execute[Email](ctx, r.client, req, opts...)
}

func (r *EmailsResource) SendEmailBatch(ctx context.Context, body *EmailBatchRequest, opts ...RequestOption) (*EmailBatchResponse, error) {
	req := &requestInput{
		op:   operations.SendEmailBatch,
		body: body,
	}

	return execute[EmailBatchResponse](ctx, r.client, req, opts...)
}

func (r *EmailsResource) UpdateEmail(ctx context.Context, emailID string, body *EmailUpdate, opts ...RequestOption) (*Email, error) {
	req := &requestInput{
		op:   operations.UpdateEmail,
		path: []string{emailID},
		body: body,
	}

	return execute[Email](ctx, r.client, req, opts...)
}
