// Code generated by epostix-codegen. DO NOT EDIT.

package epostix

import (
	"context"
	"net/url"
	"time"
)

var _ = time.Time{}
var _ = url.Values{}

type EventsResource struct {
	client *Client
}

type ListEventsParams struct {
	Limit         *int
	StartingAfter *string
	EndingBefore  *string
	EventType     *ListEventsEventType
	EmailID       *string
	DomainID      *string
	To            *string
	From          *string
	Tags          []string
	CreatedAfter  *time.Time
	CreatedBefore *time.Time
}

func (p *ListEventsParams) values() url.Values {
	out := url.Values{}
	if p == nil {
		return out
	}

	if p.Limit != nil {
		out.Set("limit", formatQueryValue(*p.Limit))
	}
	if p.StartingAfter != nil {
		out.Set("starting_after", formatQueryValue(*p.StartingAfter))
	}
	if p.EndingBefore != nil {
		out.Set("ending_before", formatQueryValue(*p.EndingBefore))
	}
	if p.EventType != nil {
		out.Set("event_type", formatQueryValue(*p.EventType))
	}
	if p.EmailID != nil {
		out.Set("email_id", formatQueryValue(*p.EmailID))
	}
	if p.DomainID != nil {
		out.Set("domain_id", formatQueryValue(*p.DomainID))
	}
	if p.To != nil {
		out.Set("to", formatQueryValue(*p.To))
	}
	if p.From != nil {
		out.Set("from", formatQueryValue(*p.From))
	}
	for _, item := range p.Tags {
		out.Add("tags", formatQueryValue(item))
	}
	if p.CreatedAfter != nil {
		out.Set("created_after", formatQueryValue(*p.CreatedAfter))
	}
	if p.CreatedBefore != nil {
		out.Set("created_before", formatQueryValue(*p.CreatedBefore))
	}

	return out
}

func (r *EventsResource) GetEvent(ctx context.Context, eventID string, opts ...RequestOption) (*Event, error) {
	req := &requestInput{
		op:   operations.GetEvent,
		path: []string{eventID},
	}

	return execute[Event](ctx, r.client, req, opts...)
}

func (r *EventsResource) ListEvents(ctx context.Context, params *ListEventsParams, opts ...RequestOption) (*EventListResponse, error) {
	req := &requestInput{
		op:    operations.ListEvents,
		query: params.values(),
	}

	return execute[EventListResponse](ctx, r.client, req, opts...)
}

func (r *EventsResource) ListEventsIterator(ctx context.Context, params *ListEventsParams, opts ...RequestOption) *Iterator[Event] {
	return newIterator[Event](ctx, r.client, &paginateInput{
		op:          operations.ListEvents,
		query:       params.values(),
		cursorParam: "starting_after",
	}, opts...)
}
