// Code generated by epostix-codegen. DO NOT EDIT.

package epostix

import (
	"context"
	"net/url"
	"time"
)

var _ = time.Time{}
var _ = url.Values{}

type InboundResource struct {
	client *Client
}

type ListInboundEmailsParams struct {
	Limit         *int
	StartingAfter *string
	EndingBefore  *string
	SpamAction    *SpamAction
	DomainID      *string
}

func (p *ListInboundEmailsParams) values() url.Values {
	out := url.Values{}
	if p == nil {
		return out
	}

	if p.Limit != nil {
		out.Set("limit", formatQueryValue(*p.Limit))
	}
	if p.StartingAfter != nil {
		out.Set("starting_after", formatQueryValue(*p.StartingAfter))
	}
	if p.EndingBefore != nil {
		out.Set("ending_before", formatQueryValue(*p.EndingBefore))
	}
	if p.SpamAction != nil {
		out.Set("spam_action", formatQueryValue(*p.SpamAction))
	}
	if p.DomainID != nil {
		out.Set("domain_id", formatQueryValue(*p.DomainID))
	}

	return out
}

func (r *InboundResource) DeleteInboundEmail(ctx context.Context, inboundID string, opts ...RequestOption) error {
	req := &requestInput{
		op:   operations.DeleteInboundEmail,
		path: []string{inboundID},
	}

	_, err := execute[struct{}](ctx, r.client, req, opts...)
	return err
}

func (r *InboundResource) GetInboundEmail(ctx context.Context, inboundID string, opts ...RequestOption) (*InboundEmail, error) {
	req := &requestInput{
		op:   operations.GetInboundEmail,
		path: []string{inboundID},
	}

	return execute[InboundEmail](ctx, r.client, req, opts...)
}

func (r *InboundResource) GetInboundEmailContent(ctx context.Context, inboundID string, opts ...RequestOption) (*InboundEmailContent, error) {
	req := &requestInput{
		op:   operations.GetInboundEmailContent,
		path: []string{inboundID},
	}

	return execute[InboundEmailContent](ctx, r.client, req, opts...)
}

func (r *InboundResource) ListInboundEmails(ctx context.Context, params *ListInboundEmailsParams, opts ...RequestOption) (*InboundEmailListResponse, error) {
	req := &requestInput{
		op:    operations.ListInboundEmails,
		query: params.values(),
	}

	return execute[InboundEmailListResponse](ctx, r.client, req, opts...)
}

func (r *InboundResource) ListInboundEmailsIterator(ctx context.Context, params *ListInboundEmailsParams, opts ...RequestOption) *Iterator[InboundEmail] {
	return newIterator[InboundEmail](ctx, r.client, &paginateInput{
		op:          operations.ListInboundEmails,
		query:       params.values(),
		cursorParam: "starting_after",
	}, opts...)
}

func (r *InboundResource) ReleaseInboundEmail(ctx context.Context, inboundID string, opts ...RequestOption) (*InboundEmail, error) {
	req := &requestInput{
		op:   operations.ReleaseInboundEmail,
		path: []string{inboundID},
	}

	return execute[InboundEmail](ctx, r.client, req, opts...)
}
