// Code generated by epostix-codegen. DO NOT EDIT.

package epostix

import (
	"encoding/json"
	"time"
)

var _ = time.Time{}
var _ = json.RawMessage{}

type AnalyticsBucket struct {
	Counts AnalyticsCounts `json:"counts"`
	Start  time.Time       `json:"start"`
}

type AnalyticsCounts struct {
	Accepted      int `json:"accepted"`
	AppleMppOpens int `json:"apple_mpp_opens"`
	Bounced       int `json:"bounced"`
	Delivered     int `json:"delivered"`
	Failed        int `json:"failed"`
	MachineOpens  int `json:"machine_opens"`
	RawClicks     int `json:"raw_clicks"`
	RawOpens      int `json:"raw_opens"`
	UniqueClicks  int `json:"unique_clicks"`
	UniqueOpens   int `json:"unique_opens"`
}

type AnalyticsSummary struct {
	AsOf   time.Time       `json:"as_of"`
	Counts AnalyticsCounts `json:"counts"`
	End    time.Time       `json:"end"`
	Start  time.Time       `json:"start"`
	Meta   ResponseMeta    `json:"-"`
}

func (m *AnalyticsSummary) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type AnalyticsTimeseries struct {
	AsOf     time.Time                   `json:"as_of"`
	Data     []AnalyticsBucket           `json:"data"`
	End      time.Time                   `json:"end"`
	Interval AnalyticsTimeseriesInterval `json:"interval"`
	Start    time.Time                   `json:"start"`
	Meta     ResponseMeta                `json:"-"`
}

func (m *AnalyticsTimeseries) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type AnalyticsTimeseriesInterval string

const (
	AnalyticsTimeseriesIntervalHour AnalyticsTimeseriesInterval = "hour"
	AnalyticsTimeseriesIntervalDay  AnalyticsTimeseriesInterval = "day"
)

var knownAnalyticsTimeseriesInterval = map[AnalyticsTimeseriesInterval]bool{
	AnalyticsTimeseriesIntervalHour: true,
	AnalyticsTimeseriesIntervalDay:  true,
}

func (v AnalyticsTimeseriesInterval) Known() bool {
	return knownAnalyticsTimeseriesInterval[v]
}

func (v AnalyticsTimeseriesInterval) String() string {
	return string(v)
}

type APIErrorPayload struct {
	Message   string        `json:"message"`
	RequestID string        `json:"request_id"`
	Status    int           `json:"status"`
	Type      APIErrorType  `json:"type"`
	Details   []ErrorDetail `json:"details,omitempty"`
	DocURL    *string       `json:"doc_url,omitempty"`
}

type APIErrorType string

const (
	APIErrorTypeInvalidRequest        APIErrorType = "invalid_request"
	APIErrorTypeValidationError       APIErrorType = "validation_error"
	APIErrorTypeUnsupportedMediaType  APIErrorType = "unsupported_media_type"
	APIErrorTypePayloadTooLarge       APIErrorType = "payload_too_large"
	APIErrorTypeMethodNotAllowed      APIErrorType = "method_not_allowed"
	APIErrorTypeNotFound              APIErrorType = "not_found"
	APIErrorTypeAuthenticationFailed  APIErrorType = "authentication_failed"
	APIErrorTypeAPIKeyExpired         APIErrorType = "api_key_expired"
	APIErrorTypeInsufficientScope     APIErrorType = "insufficient_scope"
	APIErrorTypeAPIKeyIPRestricted    APIErrorType = "api_key_ip_restricted"
	APIErrorTypeDomainScopeRestricted APIErrorType = "domain_scope_restricted"
	APIErrorTypeWorkspaceSuspended    APIErrorType = "workspace_suspended"
	APIErrorTypeTestModeRestricted    APIErrorType = "test_mode_restricted"
	APIErrorTypeDomainNotFound        APIErrorType = "domain_not_found"
	APIErrorTypeDomainNotVerified     APIErrorType = "domain_not_verified"
	APIErrorTypeInvalidFromAddress    APIErrorType = "invalid_from_address"
	APIErrorTypeDuplicateDetected     APIErrorType = "duplicate_detected"
	APIErrorTypeInvalidSchedule       APIErrorType = "invalid_schedule"
	APIErrorTypeEmailNotCancellable   APIErrorType = "email_not_cancellable"
	APIErrorTypeBatchTooLarge         APIErrorType = "batch_too_large"
	APIErrorTypeTemplateNotFound      APIErrorType = "template_not_found"
	APIErrorTypeTemplateRenderFailed  APIErrorType = "template_render_failed"
	APIErrorTypeAttachmentNotFound    APIErrorType = "attachment_not_found"
	APIErrorTypeAttachmentExpired     APIErrorType = "attachment_expired"
	APIErrorTypeAttachmentTooLarge    APIErrorType = "attachment_too_large"
	APIErrorTypeAttachmentFetchFailed APIErrorType = "attachment_fetch_failed"
	APIErrorTypeRateLimitExceeded     APIErrorType = "rate_limit_exceeded"
	APIErrorTypeDailyQuotaExceeded    APIErrorType = "daily_quota_exceeded"
	APIErrorTypeMonthlyQuotaExceeded  APIErrorType = "monthly_quota_exceeded"
	APIErrorTypeIdempotencyConflict   APIErrorType = "idempotency_conflict"
	APIErrorTypeIdempotencyInProgress APIErrorType = "idempotency_in_progress"
	APIErrorTypeAPIKeyInUse           APIErrorType = "api_key_in_use"
	APIErrorTypeWebhookLimitReached   APIErrorType = "webhook_limit_reached"
	APIErrorTypeWebhookURLNotAllowed  APIErrorType = "webhook_url_not_allowed"
	APIErrorTypeInternalError         APIErrorType = "internal_error"
	APIErrorTypeServiceUnavailable    APIErrorType = "service_unavailable"
)

var knownAPIErrorType = map[APIErrorType]bool{
	APIErrorTypeInvalidRequest:        true,
	APIErrorTypeValidationError:       true,
	APIErrorTypeUnsupportedMediaType:  true,
	APIErrorTypePayloadTooLarge:       true,
	APIErrorTypeMethodNotAllowed:      true,
	APIErrorTypeNotFound:              true,
	APIErrorTypeAuthenticationFailed:  true,
	APIErrorTypeAPIKeyExpired:         true,
	APIErrorTypeInsufficientScope:     true,
	APIErrorTypeAPIKeyIPRestricted:    true,
	APIErrorTypeDomainScopeRestricted: true,
	APIErrorTypeWorkspaceSuspended:    true,
	APIErrorTypeTestModeRestricted:    true,
	APIErrorTypeDomainNotFound:        true,
	APIErrorTypeDomainNotVerified:     true,
	APIErrorTypeInvalidFromAddress:    true,
	APIErrorTypeDuplicateDetected:     true,
	APIErrorTypeInvalidSchedule:       true,
	APIErrorTypeEmailNotCancellable:   true,
	APIErrorTypeBatchTooLarge:         true,
	APIErrorTypeTemplateNotFound:      true,
	APIErrorTypeTemplateRenderFailed:  true,
	APIErrorTypeAttachmentNotFound:    true,
	APIErrorTypeAttachmentExpired:     true,
	APIErrorTypeAttachmentTooLarge:    true,
	APIErrorTypeAttachmentFetchFailed: true,
	APIErrorTypeRateLimitExceeded:     true,
	APIErrorTypeDailyQuotaExceeded:    true,
	APIErrorTypeMonthlyQuotaExceeded:  true,
	APIErrorTypeIdempotencyConflict:   true,
	APIErrorTypeIdempotencyInProgress: true,
	APIErrorTypeAPIKeyInUse:           true,
	APIErrorTypeWebhookLimitReached:   true,
	APIErrorTypeWebhookURLNotAllowed:  true,
	APIErrorTypeInternalError:         true,
	APIErrorTypeServiceUnavailable:    true,
}

func (v APIErrorType) Known() bool {
	return knownAPIErrorType[v]
}

func (v APIErrorType) String() string {
	return string(v)
}

type APIKeyCreateRequest struct {
	ExpiresAt    time.Time                       `json:"expires_at"`
	Name         string                          `json:"name"`
	Environment  *APIKeyCreateRequestEnvironment `json:"environment,omitempty"`
	Permissions  []PermissionGrant               `json:"permissions,omitempty"`
	WhitelistIps []string                        `json:"whitelist_ips,omitempty"`
}

type APIKeyCreateRequestEnvironment string

const (
	APIKeyCreateRequestEnvironmentLive APIKeyCreateRequestEnvironment = "live"
	APIKeyCreateRequestEnvironmentTest APIKeyCreateRequestEnvironment = "test"
)

var knownAPIKeyCreateRequestEnvironment = map[APIKeyCreateRequestEnvironment]bool{
	APIKeyCreateRequestEnvironmentLive: true,
	APIKeyCreateRequestEnvironmentTest: true,
}

func (v APIKeyCreateRequestEnvironment) Known() bool {
	return knownAPIKeyCreateRequestEnvironment[v]
}

func (v APIKeyCreateRequestEnvironment) String() string {
	return string(v)
}

type APIKeyCreateResponse struct {
	CreatedAt    time.Time                       `json:"created_at"`
	Environment  APIKeyCreateResponseEnvironment `json:"environment"`
	ID           string                          `json:"id"`
	Name         string                          `json:"name"`
	Permissions  []PermissionGrant               `json:"permissions"`
	Token        string                          `json:"token"`
	TokenHint    string                          `json:"token_hint"`
	ExpiresAt    Optional[time.Time]             `json:"expires_at,omitzero"`
	WhitelistIps []string                        `json:"whitelist_ips,omitempty"`
	Meta         ResponseMeta                    `json:"-"`
}

func (m *APIKeyCreateResponse) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type APIKeyCreateResponseEnvironment string

const (
	APIKeyCreateResponseEnvironmentLive APIKeyCreateResponseEnvironment = "live"
	APIKeyCreateResponseEnvironmentTest APIKeyCreateResponseEnvironment = "test"
)

var knownAPIKeyCreateResponseEnvironment = map[APIKeyCreateResponseEnvironment]bool{
	APIKeyCreateResponseEnvironmentLive: true,
	APIKeyCreateResponseEnvironmentTest: true,
}

func (v APIKeyCreateResponseEnvironment) Known() bool {
	return knownAPIKeyCreateResponseEnvironment[v]
}

func (v APIKeyCreateResponseEnvironment) String() string {
	return string(v)
}

type APIKeyListResponse struct {
	Data       []APIKeyResponse `json:"data"`
	HasMore    *bool            `json:"has_more,omitempty"`
	NextCursor *string          `json:"next_cursor,omitempty"`
	Meta       ResponseMeta     `json:"-"`
}

func (m *APIKeyListResponse) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type APIKeyResponse struct {
	CreatedAt    time.Time                 `json:"created_at"`
	Environment  APIKeyResponseEnvironment `json:"environment"`
	ID           string                    `json:"id"`
	Name         string                    `json:"name"`
	Permissions  []PermissionGrant         `json:"permissions"`
	TokenHint    string                    `json:"token_hint"`
	ExpiresAt    Optional[time.Time]       `json:"expires_at,omitzero"`
	LastUsedAt   Optional[time.Time]       `json:"last_used_at,omitzero"`
	LastUsedIP   Optional[string]          `json:"last_used_ip,omitzero"`
	RequestCount *int                      `json:"request_count,omitempty"`
	WhitelistIps []string                  `json:"whitelist_ips,omitempty"`
	Meta         ResponseMeta              `json:"-"`
}

func (m *APIKeyResponse) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type APIKeyResponseEnvironment string

const (
	APIKeyResponseEnvironmentLive APIKeyResponseEnvironment = "live"
	APIKeyResponseEnvironmentTest APIKeyResponseEnvironment = "test"
)

var knownAPIKeyResponseEnvironment = map[APIKeyResponseEnvironment]bool{
	APIKeyResponseEnvironmentLive: true,
	APIKeyResponseEnvironmentTest: true,
}

func (v APIKeyResponseEnvironment) Known() bool {
	return knownAPIKeyResponseEnvironment[v]
}

func (v APIKeyResponseEnvironment) String() string {
	return string(v)
}

type APIKeyUpdateRequest struct {
	Name         *string           `json:"name,omitempty"`
	Permissions  []PermissionGrant `json:"permissions,omitempty"`
	WhitelistIps []string          `json:"whitelist_ips,omitempty"`
}

type APIKeyUsageListResponse struct {
	Data       []APIKeyUsageLog `json:"data"`
	HasMore    *bool            `json:"has_more,omitempty"`
	NextCursor *string          `json:"next_cursor,omitempty"`
	Meta       ResponseMeta     `json:"-"`
}

func (m *APIKeyUsageListResponse) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type APIKeyUsageLog struct {
	CreatedAt  time.Time        `json:"created_at"`
	ID         string           `json:"id"`
	Method     string           `json:"method"`
	Path       string           `json:"path"`
	StatusCode int              `json:"status_code"`
	IPAddress  Optional[string] `json:"ip_address,omitzero"`
	ScopeUsed  *PermissionScope `json:"scope_used,omitempty"`
}

type Attachment struct {
	Content            string                        `json:"content"`
	ContentType        string                        `json:"content_type"`
	Filename           string                        `json:"filename"`
	ContentDisposition *AttachmentContentDisposition `json:"content_disposition,omitempty"`
	ContentID          *string                       `json:"content_id,omitempty"`
}

type AttachmentContentDisposition string

const (
	AttachmentContentDispositionAttachment AttachmentContentDisposition = "attachment"
	AttachmentContentDispositionInline     AttachmentContentDisposition = "inline"
)

var knownAttachmentContentDisposition = map[AttachmentContentDisposition]bool{
	AttachmentContentDispositionAttachment: true,
	AttachmentContentDispositionInline:     true,
}

func (v AttachmentContentDisposition) Known() bool {
	return knownAttachmentContentDisposition[v]
}

func (v AttachmentContentDisposition) String() string {
	return string(v)
}

type AttachmentRef struct {
	AttachmentID string `json:"attachment_id"`
}

type AttachmentResponse struct {
	ContentType string       `json:"content_type"`
	ExpiresAt   time.Time    `json:"expires_at"`
	Filename    string       `json:"filename"`
	ID          string       `json:"id"`
	Size        int          `json:"size"`
	Meta        ResponseMeta `json:"-"`
}

func (m *AttachmentResponse) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type AttachmentUpload struct {
	Content     string `json:"content"`
	ContentType string `json:"content_type"`
	Filename    string `json:"filename"`
}

type AttachmentURL struct {
	ContentURL  string  `json:"content_url"`
	Filename    string  `json:"filename"`
	ContentType *string `json:"content_type,omitempty"`
}

type BounceHistoryEntry struct {
	BounceSubtype *string    `json:"bounce_subtype,omitempty"`
	BounceType    *string    `json:"bounce_type,omitempty"`
	CreatedAt     *time.Time `json:"created_at,omitempty"`
	SMTPCode      *int       `json:"smtp_code,omitempty"`
}

type Broadcast struct {
	CreatedAt       time.Time       `json:"created_at"`
	From            string          `json:"from"`
	ID              string          `json:"id"`
	Status          BroadcastStatus `json:"status"`
	Subject         string          `json:"subject"`
	UpdatedAt       time.Time       `json:"updated_at"`
	AudienceIds     []string        `json:"audience_ids,omitempty"`
	FromName        *string         `json:"from_name,omitempty"`
	Name            *string         `json:"name,omitempty"`
	ScheduledAt     *time.Time      `json:"scheduled_at,omitempty"`
	SentAt          *time.Time      `json:"sent_at,omitempty"`
	Stats           *BroadcastStats `json:"stats,omitempty"`
	TotalRecipients *int            `json:"total_recipients,omitempty"`
	Meta            ResponseMeta    `json:"-"`
}

func (m *Broadcast) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type BroadcastCreate struct {
	From        string     `json:"from"`
	Subject     string     `json:"subject"`
	AudienceIds []string   `json:"audience_ids,omitempty"`
	FromName    *string    `json:"from_name,omitempty"`
	HTML        *string    `json:"html,omitempty"`
	Preheader   *string    `json:"preheader,omitempty"`
	ScheduledAt *time.Time `json:"scheduled_at,omitempty"`
	Text        *string    `json:"text,omitempty"`
}

type BroadcastListResponse struct {
	Data       []Broadcast  `json:"data"`
	HasMore    bool         `json:"has_more"`
	NextCursor *string      `json:"next_cursor,omitempty"`
	Meta       ResponseMeta `json:"-"`
}

func (m *BroadcastListResponse) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type BroadcastStats struct {
	Accepted     *int `json:"accepted,omitempty"`
	Bounced      *int `json:"bounced,omitempty"`
	Delivered    *int `json:"delivered,omitempty"`
	Failed       *int `json:"failed,omitempty"`
	UniqueClicks *int `json:"unique_clicks,omitempty"`
	UniqueOpens  *int `json:"unique_opens,omitempty"`
}

type BroadcastStatus string

const (
	BroadcastStatusDraft     BroadcastStatus = "draft"
	BroadcastStatusScheduled BroadcastStatus = "scheduled"
	BroadcastStatusSending   BroadcastStatus = "sending"
	BroadcastStatusPaused    BroadcastStatus = "paused"
	BroadcastStatusCancelled BroadcastStatus = "cancelled"
	BroadcastStatusCompleted BroadcastStatus = "completed"
)

var knownBroadcastStatus = map[BroadcastStatus]bool{
	BroadcastStatusDraft:     true,
	BroadcastStatusScheduled: true,
	BroadcastStatusSending:   true,
	BroadcastStatusPaused:    true,
	BroadcastStatusCancelled: true,
	BroadcastStatusCompleted: true,
}

func (v BroadcastStatus) Known() bool {
	return knownBroadcastStatus[v]
}

func (v BroadcastStatus) String() string {
	return string(v)
}

type BroadcastTestRequest struct {
	Recipients []string `json:"recipients"`
}

type BroadcastTestResult struct {
	Accepted   *int         `json:"accepted,omitempty"`
	Recipients []string     `json:"recipients,omitempty"`
	Meta       ResponseMeta `json:"-"`
}

func (m *BroadcastTestResult) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type BroadcastUpdate struct {
	HTML        *string    `json:"html,omitempty"`
	Preheader   *string    `json:"preheader,omitempty"`
	ScheduledAt *time.Time `json:"scheduled_at,omitempty"`
	Subject     *string    `json:"subject,omitempty"`
	Text        *string    `json:"text,omitempty"`
}

type BulkContactCreateRequest struct {
	Contacts []ContactCreate `json:"contacts"`
}

type BulkContactCreateResponse struct {
	Created int                                         `json:"created"`
	Failed  int                                         `json:"failed"`
	Updated int                                         `json:"updated"`
	Errors  []BulkContactCreateResponseErrorsItemObject `json:"errors,omitempty"`
	Meta    ResponseMeta                                `json:"-"`
}

func (m *BulkContactCreateResponse) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type BulkContactCreateResponseErrorsItemObject struct {
	Code    *string `json:"code,omitempty"`
	Email   *string `json:"email,omitempty"`
	Index   *int    `json:"index,omitempty"`
	Message *string `json:"message,omitempty"`
}

type BulkSuppressionCreate struct {
	Emails []string `json:"emails"`
}

type BulkSuppressionError struct {
	Email   *string `json:"email,omitempty"`
	Index   *int    `json:"index,omitempty"`
	Message *string `json:"message,omitempty"`
}

type BulkSuppressionResponse struct {
	Failed    int                    `json:"failed"`
	Processed int                    `json:"processed"`
	Errors    []BulkSuppressionError `json:"errors,omitempty"`
	Meta      ResponseMeta           `json:"-"`
}

func (m *BulkSuppressionResponse) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type CancelEmailResponse struct {
	Cancelled bool         `json:"cancelled"`
	Reason    *string      `json:"reason,omitempty"`
	Meta      ResponseMeta `json:"-"`
}

func (m *CancelEmailResponse) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type Contact struct {
	CreatedAt              time.Time             `json:"created_at"`
	Email                  string                `json:"email"`
	EngagementTier         ContactEngagementTier `json:"engagement_tier"`
	ID                     string                `json:"id"`
	Source                 ContactSource         `json:"source"`
	Status                 ContactStatus         `json:"status"`
	Tags                   []Tag                 `json:"tags"`
	UpdatedAt              time.Time             `json:"updated_at"`
	CampaignsReceivedCount *int                  `json:"campaigns_received_count,omitempty"`
	LastActivityAt         Optional[time.Time]   `json:"last_activity_at,omitzero"`
	Name                   *string               `json:"name,omitempty"`
	Meta                   ResponseMeta          `json:"-"`
}

func (m *Contact) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type ContactCreate struct {
	Email  string   `json:"email"`
	Name   *string  `json:"name,omitempty"`
	TagIds []string `json:"tag_ids,omitempty"`
}

type ContactEngagementTier string

const (
	ContactEngagementTierNoData   ContactEngagementTier = "no_data"
	ContactEngagementTierNew      ContactEngagementTier = "new"
	ContactEngagementTierEngaged  ContactEngagementTier = "engaged"
	ContactEngagementTierAtRisk   ContactEngagementTier = "at_risk"
	ContactEngagementTierInactive ContactEngagementTier = "inactive"
	ContactEngagementTierCold     ContactEngagementTier = "cold"
)

var knownContactEngagementTier = map[ContactEngagementTier]bool{
	ContactEngagementTierNoData:   true,
	ContactEngagementTierNew:      true,
	ContactEngagementTierEngaged:  true,
	ContactEngagementTierAtRisk:   true,
	ContactEngagementTierInactive: true,
	ContactEngagementTierCold:     true,
}

func (v ContactEngagementTier) Known() bool {
	return knownContactEngagementTier[v]
}

func (v ContactEngagementTier) String() string {
	return string(v)
}

type ContactListResponse struct {
	Data       []Contact    `json:"data"`
	HasMore    bool         `json:"has_more"`
	NextCursor *string      `json:"next_cursor,omitempty"`
	Meta       ResponseMeta `json:"-"`
}

func (m *ContactListResponse) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type ContactSource string

const (
	ContactSourceAPI       ContactSource = "api"
	ContactSourceBulkAPI   ContactSource = "bulk_api"
	ContactSourceCsvImport ContactSource = "csv_import"
	ContactSourceSMTP      ContactSource = "smtp"
	ContactSourceForm      ContactSource = "form"
	ContactSourceUnknown   ContactSource = "unknown"
)

var knownContactSource = map[ContactSource]bool{
	ContactSourceAPI:       true,
	ContactSourceBulkAPI:   true,
	ContactSourceCsvImport: true,
	ContactSourceSMTP:      true,
	ContactSourceForm:      true,
	ContactSourceUnknown:   true,
}

func (v ContactSource) Known() bool {
	return knownContactSource[v]
}

func (v ContactSource) String() string {
	return string(v)
}

type ContactStatus string

const (
	ContactStatusSubscribed   ContactStatus = "subscribed"
	ContactStatusUnsubscribed ContactStatus = "unsubscribed"
	ContactStatusCleaned      ContactStatus = "cleaned"
)

var knownContactStatus = map[ContactStatus]bool{
	ContactStatusSubscribed:   true,
	ContactStatusUnsubscribed: true,
	ContactStatusCleaned:      true,
}

func (v ContactStatus) Known() bool {
	return knownContactStatus[v]
}

func (v ContactStatus) String() string {
	return string(v)
}

type ContactUpdate struct {
	Name   *string  `json:"name,omitempty"`
	TagIds []string `json:"tag_ids,omitempty"`
}

type ContactUpsert struct {
	Name   *string  `json:"name,omitempty"`
	TagIds []string `json:"tag_ids,omitempty"`
}

type DNSRecord struct {
	Host                  string           `json:"host"`
	Purpose               DNSRecordPurpose `json:"purpose"`
	Required              bool             `json:"required"`
	Status                DNSRecordStatus  `json:"status"`
	Type                  DNSRecordType    `json:"type"`
	Value                 string           `json:"value"`
	Kind                  *DNSRecordKind   `json:"kind,omitempty"`
	LastVerificationError *string          `json:"last_verification_error,omitempty"`
	Priority              *int             `json:"priority,omitempty"`
}

type DNSRecordKind string

const (
	DNSRecordKindSPF        DNSRecordKind = "spf"
	DNSRecordKindDKIM       DNSRecordKind = "dkim"
	DNSRecordKindDMARC      DNSRecordKind = "dmarc"
	DNSRecordKindMXInbound  DNSRecordKind = "mx_inbound"
	DNSRecordKindOpenpgpkey DNSRecordKind = "openpgpkey"
)

var knownDNSRecordKind = map[DNSRecordKind]bool{
	DNSRecordKindSPF:        true,
	DNSRecordKindDKIM:       true,
	DNSRecordKindDMARC:      true,
	DNSRecordKindMXInbound:  true,
	DNSRecordKindOpenpgpkey: true,
}

func (v DNSRecordKind) Known() bool {
	return knownDNSRecordKind[v]
}

func (v DNSRecordKind) String() string {
	return string(v)
}

type DNSRecordPurpose string

const (
	DNSRecordPurposeSending   DNSRecordPurpose = "sending"
	DNSRecordPurposeReceiving DNSRecordPurpose = "receiving"
)

var knownDNSRecordPurpose = map[DNSRecordPurpose]bool{
	DNSRecordPurposeSending:   true,
	DNSRecordPurposeReceiving: true,
}

func (v DNSRecordPurpose) Known() bool {
	return knownDNSRecordPurpose[v]
}

func (v DNSRecordPurpose) String() string {
	return string(v)
}

type DNSRecordStatus string

const (
	DNSRecordStatusUnverified DNSRecordStatus = "unverified"
	DNSRecordStatusVerifying  DNSRecordStatus = "verifying"
	DNSRecordStatusActive     DNSRecordStatus = "active"
	DNSRecordStatusFailed     DNSRecordStatus = "failed"
)

var knownDNSRecordStatus = map[DNSRecordStatus]bool{
	DNSRecordStatusUnverified: true,
	DNSRecordStatusVerifying:  true,
	DNSRecordStatusActive:     true,
	DNSRecordStatusFailed:     true,
}

func (v DNSRecordStatus) Known() bool {
	return knownDNSRecordStatus[v]
}

func (v DNSRecordStatus) String() string {
	return string(v)
}

type DNSRecordType string

const (
	DNSRecordTypeTxt DNSRecordType = "TXT"
	DNSRecordTypeMX  DNSRecordType = "MX"
)

var knownDNSRecordType = map[DNSRecordType]bool{
	DNSRecordTypeTxt: true,
	DNSRecordTypeMX:  true,
}

func (v DNSRecordType) Known() bool {
	return knownDNSRecordType[v]
}

func (v DNSRecordType) String() string {
	return string(v)
}

type Domain struct {
	CreatedAt        time.Time                  `json:"created_at"`
	DNSRecords       []DNSRecord                `json:"dns_records"`
	ID               string                     `json:"id"`
	Name             string                     `json:"name"`
	Region           string                     `json:"region"`
	Status           DomainStatus               `json:"status"`
	ClickTracking    *DomainClickTrackingObject `json:"click_tracking,omitempty"`
	LastDNSCheckAt   Optional[time.Time]        `json:"last_dns_check_at,omitzero"`
	OpenTracking     *DomainOpenTrackingObject  `json:"open_tracking,omitempty"`
	SendingSubdomain *string                    `json:"sending_subdomain,omitempty"`
	UpdatedAt        *time.Time                 `json:"updated_at,omitempty"`
	Meta             ResponseMeta               `json:"-"`
}

func (m *Domain) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type DomainClickTrackingObject struct {
	Marketing     *bool `json:"marketing,omitempty"`
	Transactional *bool `json:"transactional,omitempty"`
}

type DomainCreateRequest struct {
	Name             string  `json:"name"`
	Region           *string `json:"region,omitempty"`
	SendingSubdomain *string `json:"sending_subdomain,omitempty"`
}

type DomainListResponse struct {
	Data       []Domain     `json:"data"`
	HasMore    bool         `json:"has_more"`
	NextCursor *string      `json:"next_cursor,omitempty"`
	Meta       ResponseMeta `json:"-"`
}

func (m *DomainListResponse) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type DomainOpenTrackingObject struct {
	Marketing     *bool `json:"marketing,omitempty"`
	Transactional *bool `json:"transactional,omitempty"`
}

type DomainStatus string

const (
	DomainStatusUnverified DomainStatus = "unverified"
	DomainStatusVerifying  DomainStatus = "verifying"
	DomainStatusActive     DomainStatus = "active"
)

var knownDomainStatus = map[DomainStatus]bool{
	DomainStatusUnverified: true,
	DomainStatusVerifying:  true,
	DomainStatusActive:     true,
}

func (v DomainStatus) Known() bool {
	return knownDomainStatus[v]
}

func (v DomainStatus) String() string {
	return string(v)
}

type DomainUpdate struct {
	ClickTracking *DomainUpdateClickTrackingObject `json:"click_tracking,omitempty"`
	OpenTracking  *DomainUpdateOpenTrackingObject  `json:"open_tracking,omitempty"`
}

type DomainUpdateClickTrackingObject struct {
	Marketing     *bool `json:"marketing,omitempty"`
	Transactional *bool `json:"transactional,omitempty"`
}

type DomainUpdateOpenTrackingObject struct {
	Marketing     *bool `json:"marketing,omitempty"`
	Transactional *bool `json:"transactional,omitempty"`
}

type Email struct {
	CreatedAt       time.Time         `json:"created_at"`
	ID              string            `json:"id"`
	Status          EmailStatus       `json:"status"`
	UpdatedAt       time.Time         `json:"updated_at"`
	BatchID         *string           `json:"batch_id,omitempty"`
	Bcc             []string          `json:"bcc,omitempty"`
	Cc              []string          `json:"cc,omitempty"`
	ClickCount      *int              `json:"click_count,omitempty"`
	DeliveryTimeMs  *int              `json:"delivery_time_ms,omitempty"`
	ErrorMessage    *string           `json:"error_message,omitempty"`
	Events          []EmailEvent      `json:"events,omitempty"`
	From            *string           `json:"from,omitempty"`
	Headers         map[string]string `json:"headers,omitempty"`
	HTML            *string           `json:"html,omitempty"`
	Metadata        json.RawMessage   `json:"metadata,omitempty"`
	Mode            *EmailMode        `json:"mode,omitempty"`
	OpenCount       *int              `json:"open_count,omitempty"`
	PreflightResult *PreflightResult  `json:"preflight_result,omitempty"`
	ReplyTo         *string           `json:"reply_to,omitempty"`
	ScheduledAt     *time.Time        `json:"scheduled_at,omitempty"`
	Subject         *string           `json:"subject,omitempty"`
	Tags            []string          `json:"tags,omitempty"`
	TemplateData    map[string]string `json:"template_data,omitempty"`
	TemplateID      *string           `json:"template_id,omitempty"`
	TemplateVersion *int              `json:"template_version,omitempty"`
	Text            *string           `json:"text,omitempty"`
	To              []string          `json:"to,omitempty"`
	Tracking        *TrackingOptions  `json:"tracking,omitempty"`
	Meta            ResponseMeta      `json:"-"`
}

func (m *Email) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type EmailBatchError struct {
	Code    string `json:"code"`
	Index   int    `json:"index"`
	Message string `json:"message"`
}

type EmailBatchRequest struct {
	Emails     []EmailCreate                `json:"emails"`
	Validation *EmailBatchRequestValidation `json:"validation,omitempty"`
}

type EmailBatchRequestValidation string

const (
	EmailBatchRequestValidationStrict     EmailBatchRequestValidation = "strict"
	EmailBatchRequestValidationPermissive EmailBatchRequestValidation = "permissive"
)

var knownEmailBatchRequestValidation = map[EmailBatchRequestValidation]bool{
	EmailBatchRequestValidationStrict:     true,
	EmailBatchRequestValidationPermissive: true,
}

func (v EmailBatchRequestValidation) Known() bool {
	return knownEmailBatchRequestValidation[v]
}

func (v EmailBatchRequestValidation) String() string {
	return string(v)
}

type EmailBatchResponse struct {
	BatchID string             `json:"batch_id"`
	Results []EmailBatchResult `json:"results"`
	Errors  []EmailBatchError  `json:"errors,omitempty"`
	Meta    ResponseMeta       `json:"-"`
}

func (m *EmailBatchResponse) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type EmailBatchResult struct {
	Index  int                    `json:"index"`
	Status EmailBatchResultStatus `json:"status"`
	Error  *APIErrorPayload       `json:"error,omitempty"`
	ID     *string                `json:"id,omitempty"`
}

type EmailBatchResultStatus string

const (
	EmailBatchResultStatusPending   EmailBatchResultStatus = "pending"
	EmailBatchResultStatusScheduled EmailBatchResultStatus = "scheduled"
	EmailBatchResultStatusFailed    EmailBatchResultStatus = "failed"
)

var knownEmailBatchResultStatus = map[EmailBatchResultStatus]bool{
	EmailBatchResultStatusPending:   true,
	EmailBatchResultStatusScheduled: true,
	EmailBatchResultStatusFailed:    true,
}

func (v EmailBatchResultStatus) Known() bool {
	return knownEmailBatchResultStatus[v]
}

func (v EmailBatchResultStatus) String() string {
	return string(v)
}

type EmailCreate struct {
	From            Mailbox                      `json:"from"`
	Subject         string                       `json:"subject"`
	To              []string                     `json:"to"`
	AllowDuplicate  *bool                        `json:"allow_duplicate,omitempty"`
	Attachments     []EmailCreateAttachmentsItem `json:"attachments,omitempty"`
	Bcc             []string                     `json:"bcc,omitempty"`
	Cc              []string                     `json:"cc,omitempty"`
	Headers         map[string]string            `json:"headers,omitempty"`
	HTML            *string                      `json:"html,omitempty"`
	Metadata        json.RawMessage              `json:"metadata,omitempty"`
	Preflight       *PreflightOptions            `json:"preflight,omitempty"`
	ReplyTo         *Mailbox                     `json:"reply_to,omitempty"`
	ScheduledAt     *time.Time                   `json:"scheduled_at,omitempty"`
	Tags            []string                     `json:"tags,omitempty"`
	TemplateData    map[string]string            `json:"template_data,omitempty"`
	TemplateID      *string                      `json:"template_id,omitempty"`
	TemplateVersion *int                         `json:"template_version,omitempty"`
	Text            *string                      `json:"text,omitempty"`
	Tracking        *TrackingOptions             `json:"tracking,omitempty"`
}

type EmailCreateAttachmentsItem interface {
	isEmailCreateAttachmentsItem()
}

func (Attachment) isEmailCreateAttachmentsItem()    {}
func (AttachmentRef) isEmailCreateAttachmentsItem() {}
func (AttachmentURL) isEmailCreateAttachmentsItem() {}

type EmailEvent struct {
	CreatedAt time.Time `json:"created_at"`
	Status    string    `json:"status"`
	EventType *string   `json:"event_type,omitempty"`
}

type EmailListResponse struct {
	Data       []Email      `json:"data"`
	HasMore    bool         `json:"has_more"`
	NextCursor *string      `json:"next_cursor,omitempty"`
	Meta       ResponseMeta `json:"-"`
}

func (m *EmailListResponse) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type EmailMode string

const (
	EmailModeLive EmailMode = "live"
	EmailModeTest EmailMode = "test"
)

var knownEmailMode = map[EmailMode]bool{
	EmailModeLive: true,
	EmailModeTest: true,
}

func (v EmailMode) Known() bool {
	return knownEmailMode[v]
}

func (v EmailMode) String() string {
	return string(v)
}

type EmailStatus string

const (
	EmailStatusPending   EmailStatus = "pending"
	EmailStatusScheduled EmailStatus = "scheduled"
	EmailStatusSent      EmailStatus = "sent"
	EmailStatusDelivered EmailStatus = "delivered"
	EmailStatusFailed    EmailStatus = "failed"
	EmailStatusCancelled EmailStatus = "cancelled"
)

var knownEmailStatus = map[EmailStatus]bool{
	EmailStatusPending:   true,
	EmailStatusScheduled: true,
	EmailStatusSent:      true,
	EmailStatusDelivered: true,
	EmailStatusFailed:    true,
	EmailStatusCancelled: true,
}

func (v EmailStatus) Known() bool {
	return knownEmailStatus[v]
}

func (v EmailStatus) String() string {
	return string(v)
}

type EmailUpdate struct {
	ScheduledAt Optional[time.Time] `json:"scheduled_at,omitzero"`
}

type Event struct {
	CreatedAt time.Time       `json:"created_at"`
	Data      json.RawMessage `json:"data"`
	ID        string          `json:"id"`
	Type      EventType       `json:"type"`
	EmailID   *string         `json:"email_id,omitempty"`
	InboundID *string         `json:"inbound_id,omitempty"`
	Meta      ResponseMeta    `json:"-"`
}

func (m *Event) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type EventListResponse struct {
	Data       []Event      `json:"data"`
	HasMore    bool         `json:"has_more"`
	NextCursor *string      `json:"next_cursor,omitempty"`
	Meta       ResponseMeta `json:"-"`
}

func (m *EventListResponse) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type EventType string

const (
	EventTypeEmailSent                        EventType = "email.sent"
	EventTypeEmailDelivered                   EventType = "email.delivered"
	EventTypeEmailBounced                     EventType = "email.bounced"
	EventTypeEmailOpened                      EventType = "email.opened"
	EventTypeEmailClicked                     EventType = "email.clicked"
	EventTypeEmailComplained                  EventType = "email.complained"
	EventTypeEmailFailed                      EventType = "email.failed"
	EventTypeEmailDelayed                     EventType = "email.delayed"
	EventTypeEmailCancelled                   EventType = "email.cancelled"
	EventTypeEmailReceived                    EventType = "email.received"
	EventTypeDomainVerified                   EventType = "domain.verified"
	EventTypeDomainVerificationFailed         EventType = "domain.verification_failed"
	EventTypeTrackingDomainVerified           EventType = "tracking_domain.verified"
	EventTypeTrackingDomainVerificationFailed EventType = "tracking_domain.verification_failed"
	EventTypeCampaignStarted                  EventType = "campaign.started"
	EventTypeCampaignPaused                   EventType = "campaign.paused"
	EventTypeCampaignResumed                  EventType = "campaign.resumed"
	EventTypeCampaignCompleted                EventType = "campaign.completed"
	EventTypeCampaignCancelled                EventType = "campaign.cancelled"
	EventTypeCampaignAutoPaused               EventType = "campaign.auto_paused"
	EventTypeContactStatusChanged             EventType = "contact.status_changed"
	EventTypeContactImportCompleted           EventType = "contact.import_completed"
	EventTypeSuppressionCreated               EventType = "suppression.created"
	EventTypeSuppressionRemoved               EventType = "suppression.removed"
	EventTypeWebhookTest                      EventType = "webhook.test"
)

var knownEventType = map[EventType]bool{
	EventTypeEmailSent:                        true,
	EventTypeEmailDelivered:                   true,
	EventTypeEmailBounced:                     true,
	EventTypeEmailOpened:                      true,
	EventTypeEmailClicked:                     true,
	EventTypeEmailComplained:                  true,
	EventTypeEmailFailed:                      true,
	EventTypeEmailDelayed:                     true,
	EventTypeEmailCancelled:                   true,
	EventTypeEmailReceived:                    true,
	EventTypeDomainVerified:                   true,
	EventTypeDomainVerificationFailed:         true,
	EventTypeTrackingDomainVerified:           true,
	EventTypeTrackingDomainVerificationFailed: true,
	EventTypeCampaignStarted:                  true,
	EventTypeCampaignPaused:                   true,
	EventTypeCampaignResumed:                  true,
	EventTypeCampaignCompleted:                true,
	EventTypeCampaignCancelled:                true,
	EventTypeCampaignAutoPaused:               true,
	EventTypeContactStatusChanged:             true,
	EventTypeContactImportCompleted:           true,
	EventTypeSuppressionCreated:               true,
	EventTypeSuppressionRemoved:               true,
	EventTypeWebhookTest:                      true,
}

func (v EventType) Known() bool {
	return knownEventType[v]
}

func (v EventType) String() string {
	return string(v)
}

type GetAnalyticsSummaryPurpose string

const (
	GetAnalyticsSummaryPurposeAll           GetAnalyticsSummaryPurpose = "all"
	GetAnalyticsSummaryPurposeTransactional GetAnalyticsSummaryPurpose = "transactional"
	GetAnalyticsSummaryPurposeMarketing     GetAnalyticsSummaryPurpose = "marketing"
)

var knownGetAnalyticsSummaryPurpose = map[GetAnalyticsSummaryPurpose]bool{
	GetAnalyticsSummaryPurposeAll:           true,
	GetAnalyticsSummaryPurposeTransactional: true,
	GetAnalyticsSummaryPurposeMarketing:     true,
}

func (v GetAnalyticsSummaryPurpose) Known() bool {
	return knownGetAnalyticsSummaryPurpose[v]
}

func (v GetAnalyticsSummaryPurpose) String() string {
	return string(v)
}

type GetAnalyticsTimeseriesInterval string

const (
	GetAnalyticsTimeseriesIntervalHour GetAnalyticsTimeseriesInterval = "hour"
	GetAnalyticsTimeseriesIntervalDay  GetAnalyticsTimeseriesInterval = "day"
)

var knownGetAnalyticsTimeseriesInterval = map[GetAnalyticsTimeseriesInterval]bool{
	GetAnalyticsTimeseriesIntervalHour: true,
	GetAnalyticsTimeseriesIntervalDay:  true,
}

func (v GetAnalyticsTimeseriesInterval) Known() bool {
	return knownGetAnalyticsTimeseriesInterval[v]
}

func (v GetAnalyticsTimeseriesInterval) String() string {
	return string(v)
}

type GetAnalyticsTimeseriesPurpose string

const (
	GetAnalyticsTimeseriesPurposeAll           GetAnalyticsTimeseriesPurpose = "all"
	GetAnalyticsTimeseriesPurposeTransactional GetAnalyticsTimeseriesPurpose = "transactional"
	GetAnalyticsTimeseriesPurposeMarketing     GetAnalyticsTimeseriesPurpose = "marketing"
)

var knownGetAnalyticsTimeseriesPurpose = map[GetAnalyticsTimeseriesPurpose]bool{
	GetAnalyticsTimeseriesPurposeAll:           true,
	GetAnalyticsTimeseriesPurposeTransactional: true,
	GetAnalyticsTimeseriesPurposeMarketing:     true,
}

func (v GetAnalyticsTimeseriesPurpose) Known() bool {
	return knownGetAnalyticsTimeseriesPurpose[v]
}

func (v GetAnalyticsTimeseriesPurpose) String() string {
	return string(v)
}

type InboundEmail struct {
	AttachmentCount int          `json:"attachment_count"`
	DomainID        string       `json:"domain_id"`
	From            string       `json:"from"`
	ID              string       `json:"id"`
	ReceivedAt      time.Time    `json:"received_at"`
	SizeBytes       int          `json:"size_bytes"`
	SpamAction      SpamAction   `json:"spam_action"`
	SpamScore       float64      `json:"spam_score"`
	Subject         string       `json:"subject"`
	To              []string     `json:"to"`
	MessageID       *string      `json:"message_id,omitempty"`
	Meta            ResponseMeta `json:"-"`
}

func (m *InboundEmail) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type InboundEmailAttachment struct {
	ContentID   *string `json:"content_id,omitempty"`
	ContentType *string `json:"content_type,omitempty"`
	Filename    *string `json:"filename,omitempty"`
	SizeBytes   *int    `json:"size_bytes,omitempty"`
}

type InboundEmailContent struct {
	ID          string                   `json:"id"`
	Attachments []InboundEmailAttachment `json:"attachments,omitempty"`
	From        *string                  `json:"from,omitempty"`
	HTML        *string                  `json:"html,omitempty"`
	Subject     *string                  `json:"subject,omitempty"`
	Text        *string                  `json:"text,omitempty"`
	To          []string                 `json:"to,omitempty"`
	Meta        ResponseMeta             `json:"-"`
}

func (m *InboundEmailContent) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type InboundEmailListResponse struct {
	Data       []InboundEmail `json:"data"`
	HasMore    bool           `json:"has_more"`
	NextCursor *string        `json:"next_cursor,omitempty"`
	Meta       ResponseMeta   `json:"-"`
}

func (m *InboundEmailListResponse) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type ListContactsEngagementTier string

const (
	ListContactsEngagementTierNoData   ListContactsEngagementTier = "no_data"
	ListContactsEngagementTierNew      ListContactsEngagementTier = "new"
	ListContactsEngagementTierEngaged  ListContactsEngagementTier = "engaged"
	ListContactsEngagementTierAtRisk   ListContactsEngagementTier = "at_risk"
	ListContactsEngagementTierInactive ListContactsEngagementTier = "inactive"
	ListContactsEngagementTierCold     ListContactsEngagementTier = "cold"
)

var knownListContactsEngagementTier = map[ListContactsEngagementTier]bool{
	ListContactsEngagementTierNoData:   true,
	ListContactsEngagementTierNew:      true,
	ListContactsEngagementTierEngaged:  true,
	ListContactsEngagementTierAtRisk:   true,
	ListContactsEngagementTierInactive: true,
	ListContactsEngagementTierCold:     true,
}

func (v ListContactsEngagementTier) Known() bool {
	return knownListContactsEngagementTier[v]
}

func (v ListContactsEngagementTier) String() string {
	return string(v)
}

type ListContactsStatus string

const (
	ListContactsStatusSubscribed   ListContactsStatus = "subscribed"
	ListContactsStatusUnsubscribed ListContactsStatus = "unsubscribed"
	ListContactsStatusCleaned      ListContactsStatus = "cleaned"
)

var knownListContactsStatus = map[ListContactsStatus]bool{
	ListContactsStatusSubscribed:   true,
	ListContactsStatusUnsubscribed: true,
	ListContactsStatusCleaned:      true,
}

func (v ListContactsStatus) Known() bool {
	return knownListContactsStatus[v]
}

func (v ListContactsStatus) String() string {
	return string(v)
}

type ListDomainsStatus string

const (
	ListDomainsStatusUnverified ListDomainsStatus = "unverified"
	ListDomainsStatusVerifying  ListDomainsStatus = "verifying"
	ListDomainsStatusActive     ListDomainsStatus = "active"
)

var knownListDomainsStatus = map[ListDomainsStatus]bool{
	ListDomainsStatusUnverified: true,
	ListDomainsStatusVerifying:  true,
	ListDomainsStatusActive:     true,
}

func (v ListDomainsStatus) Known() bool {
	return knownListDomainsStatus[v]
}

func (v ListDomainsStatus) String() string {
	return string(v)
}

type ListEmailsStatus string

const (
	ListEmailsStatusPending   ListEmailsStatus = "pending"
	ListEmailsStatusScheduled ListEmailsStatus = "scheduled"
	ListEmailsStatusSent      ListEmailsStatus = "sent"
	ListEmailsStatusDelivered ListEmailsStatus = "delivered"
	ListEmailsStatusFailed    ListEmailsStatus = "failed"
	ListEmailsStatusCancelled ListEmailsStatus = "cancelled"
)

var knownListEmailsStatus = map[ListEmailsStatus]bool{
	ListEmailsStatusPending:   true,
	ListEmailsStatusScheduled: true,
	ListEmailsStatusSent:      true,
	ListEmailsStatusDelivered: true,
	ListEmailsStatusFailed:    true,
	ListEmailsStatusCancelled: true,
}

func (v ListEmailsStatus) Known() bool {
	return knownListEmailsStatus[v]
}

func (v ListEmailsStatus) String() string {
	return string(v)
}

type ListEventsEventType string

const (
	ListEventsEventTypeSent       ListEventsEventType = "sent"
	ListEventsEventTypeDelivered  ListEventsEventType = "delivered"
	ListEventsEventTypeBounced    ListEventsEventType = "bounced"
	ListEventsEventTypeOpened     ListEventsEventType = "opened"
	ListEventsEventTypeClicked    ListEventsEventType = "clicked"
	ListEventsEventTypeComplained ListEventsEventType = "complained"
	ListEventsEventTypeFailed     ListEventsEventType = "failed"
	ListEventsEventTypeDelayed    ListEventsEventType = "delayed"
)

var knownListEventsEventType = map[ListEventsEventType]bool{
	ListEventsEventTypeSent:       true,
	ListEventsEventTypeDelivered:  true,
	ListEventsEventTypeBounced:    true,
	ListEventsEventTypeOpened:     true,
	ListEventsEventTypeClicked:    true,
	ListEventsEventTypeComplained: true,
	ListEventsEventTypeFailed:     true,
	ListEventsEventTypeDelayed:    true,
}

func (v ListEventsEventType) Known() bool {
	return knownListEventsEventType[v]
}

func (v ListEventsEventType) String() string {
	return string(v)
}

type ListSuppressionsReason string

const (
	ListSuppressionsReasonHardBounce  ListSuppressionsReason = "hard_bounce"
	ListSuppressionsReasonSoftBounce  ListSuppressionsReason = "soft_bounce"
	ListSuppressionsReasonComplaint   ListSuppressionsReason = "complaint"
	ListSuppressionsReasonManual      ListSuppressionsReason = "manual"
	ListSuppressionsReasonUnsubscribe ListSuppressionsReason = "unsubscribe"
)

var knownListSuppressionsReason = map[ListSuppressionsReason]bool{
	ListSuppressionsReasonHardBounce:  true,
	ListSuppressionsReasonSoftBounce:  true,
	ListSuppressionsReasonComplaint:   true,
	ListSuppressionsReasonManual:      true,
	ListSuppressionsReasonUnsubscribe: true,
}

func (v ListSuppressionsReason) Known() bool {
	return knownListSuppressionsReason[v]
}

func (v ListSuppressionsReason) String() string {
	return string(v)
}

type ListWebhookLogsStatus string

const (
	ListWebhookLogsStatusPending ListWebhookLogsStatus = "pending"
	ListWebhookLogsStatusSuccess ListWebhookLogsStatus = "success"
	ListWebhookLogsStatusFailed  ListWebhookLogsStatus = "failed"
)

var knownListWebhookLogsStatus = map[ListWebhookLogsStatus]bool{
	ListWebhookLogsStatusPending: true,
	ListWebhookLogsStatusSuccess: true,
	ListWebhookLogsStatusFailed:  true,
}

func (v ListWebhookLogsStatus) Known() bool {
	return knownListWebhookLogsStatus[v]
}

func (v ListWebhookLogsStatus) String() string {
	return string(v)
}

type MailboxAddressValue struct {
	Email string  `json:"email"`
	Name  *string `json:"name,omitempty"`
}

type PermissionGrant = string

type PermissionScope string

const (
	PermissionScopeSending            PermissionScope = "sending"
	PermissionScopeEmailsRead         PermissionScope = "emails:read"
	PermissionScopeDomainsManage      PermissionScope = "domains:manage"
	PermissionScopeContactsManage     PermissionScope = "contacts:manage"
	PermissionScopeWebhooksManage     PermissionScope = "webhooks:manage"
	PermissionScopeAnalyticsRead      PermissionScope = "analytics:read"
	PermissionScopeAPIKeysManage      PermissionScope = "api-keys:manage"
	PermissionScopeSuppressionsRead   PermissionScope = "suppressions:read"
	PermissionScopeSuppressionsManage PermissionScope = "suppressions:manage"
	PermissionScopeTemplatesRead      PermissionScope = "templates:read"
	PermissionScopeTemplatesManage    PermissionScope = "templates:manage"
	PermissionScopeInboundRead        PermissionScope = "inbound:read"
	PermissionScopeInboundManage      PermissionScope = "inbound:manage"
	PermissionScopeBroadcastsRead     PermissionScope = "broadcasts:read"
	PermissionScopeBroadcastsManage   PermissionScope = "broadcasts:manage"
	PermissionScopeBroadcastsSend     PermissionScope = "broadcasts:send"
	PermissionScopeAll                PermissionScope = "*"
)

var knownPermissionScope = map[PermissionScope]bool{
	PermissionScopeSending:            true,
	PermissionScopeEmailsRead:         true,
	PermissionScopeDomainsManage:      true,
	PermissionScopeContactsManage:     true,
	PermissionScopeWebhooksManage:     true,
	PermissionScopeAnalyticsRead:      true,
	PermissionScopeAPIKeysManage:      true,
	PermissionScopeSuppressionsRead:   true,
	PermissionScopeSuppressionsManage: true,
	PermissionScopeTemplatesRead:      true,
	PermissionScopeTemplatesManage:    true,
	PermissionScopeInboundRead:        true,
	PermissionScopeInboundManage:      true,
	PermissionScopeBroadcastsRead:     true,
	PermissionScopeBroadcastsManage:   true,
	PermissionScopeBroadcastsSend:     true,
	PermissionScopeAll:                true,
}

func (v PermissionScope) Known() bool {
	return knownPermissionScope[v]
}

func (v PermissionScope) String() string {
	return string(v)
}

type PreflightOptions struct {
	SpamCheck *bool `json:"spam_check,omitempty"`
	Validate  *bool `json:"validate,omitempty"`
}

type PreflightResult struct {
	SpamAction       *string       `json:"spam_action,omitempty"`
	SpamScore        *float64      `json:"spam_score,omitempty"`
	ValidationErrors []ErrorDetail `json:"validation_errors,omitempty"`
}

type SpamAction string

const (
	SpamActionNoAction       SpamAction = "no_action"
	SpamActionGreylist       SpamAction = "greylist"
	SpamActionAddHeader      SpamAction = "add_header"
	SpamActionRewriteSubject SpamAction = "rewrite_subject"
	SpamActionSoftReject     SpamAction = "soft_reject"
	SpamActionReject         SpamAction = "reject"
	SpamActionDiscard        SpamAction = "discard"
	SpamActionQuarantine     SpamAction = "quarantine"
)

var knownSpamAction = map[SpamAction]bool{
	SpamActionNoAction:       true,
	SpamActionGreylist:       true,
	SpamActionAddHeader:      true,
	SpamActionRewriteSubject: true,
	SpamActionSoftReject:     true,
	SpamActionReject:         true,
	SpamActionDiscard:        true,
	SpamActionQuarantine:     true,
}

func (v SpamAction) Known() bool {
	return knownSpamAction[v]
}

func (v SpamAction) String() string {
	return string(v)
}

type SpamCheckDetails struct {
	HasHTMLPart        *bool    `json:"has_html_part,omitempty"`
	HasListUnsubscribe *bool    `json:"has_list_unsubscribe,omitempty"`
	HasTextPart        *bool    `json:"has_text_part,omitempty"`
	ImageCount         *int     `json:"image_count,omitempty"`
	LinkCount          *int     `json:"link_count,omitempty"`
	TextToHTMLRatio    *float64 `json:"text_to_html_ratio,omitempty"`
}

type SpamCheckResult struct {
	Action    *string                 `json:"action,omitempty"`
	Details   *SpamCheckDetails       `json:"details,omitempty"`
	Issues    []SpamIssue             `json:"issues,omitempty"`
	Rules     []SpamRule              `json:"rules,omitempty"`
	Score     *float64                `json:"score,omitempty"`
	Threshold *float64                `json:"threshold,omitempty"`
	Verdict   *SpamCheckResultVerdict `json:"verdict,omitempty"`
	Meta      ResponseMeta            `json:"-"`
}

func (m *SpamCheckResult) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type SpamCheckResultVerdict string

const (
	SpamCheckResultVerdictPass SpamCheckResultVerdict = "pass"
	SpamCheckResultVerdictWarn SpamCheckResultVerdict = "warn"
	SpamCheckResultVerdictFail SpamCheckResultVerdict = "fail"
)

var knownSpamCheckResultVerdict = map[SpamCheckResultVerdict]bool{
	SpamCheckResultVerdictPass: true,
	SpamCheckResultVerdictWarn: true,
	SpamCheckResultVerdictFail: true,
}

func (v SpamCheckResultVerdict) Known() bool {
	return knownSpamCheckResultVerdict[v]
}

func (v SpamCheckResultVerdict) String() string {
	return string(v)
}

type SpamIssue struct {
	Code       *string            `json:"code,omitempty"`
	Message    *string            `json:"message,omitempty"`
	Severity   *SpamIssueSeverity `json:"severity,omitempty"`
	Suggestion *string            `json:"suggestion,omitempty"`
}

type SpamIssueSeverity string

const (
	SpamIssueSeverityWarning SpamIssueSeverity = "warning"
	SpamIssueSeverityError   SpamIssueSeverity = "error"
)

var knownSpamIssueSeverity = map[SpamIssueSeverity]bool{
	SpamIssueSeverityWarning: true,
	SpamIssueSeverityError:   true,
}

func (v SpamIssueSeverity) Known() bool {
	return knownSpamIssueSeverity[v]
}

func (v SpamIssueSeverity) String() string {
	return string(v)
}

type SpamRule struct {
	Description *string  `json:"description,omitempty"`
	Name        *string  `json:"name,omitempty"`
	Score       *float64 `json:"score,omitempty"`
	Suggestion  *string  `json:"suggestion,omitempty"`
}

type Suppression struct {
	CreatedAt time.Time         `json:"created_at"`
	Email     string            `json:"email"`
	ID        string            `json:"id"`
	Reason    SuppressionReason `json:"reason"`
	Meta      ResponseMeta      `json:"-"`
}

func (m *Suppression) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type SuppressionCreate struct {
	Email string `json:"email"`
}

type SuppressionDetail struct {
	Email         string                   `json:"email"`
	Suppressed    bool                     `json:"suppressed"`
	BounceHistory []BounceHistoryEntry     `json:"bounce_history,omitempty"`
	CreatedAt     *time.Time               `json:"created_at,omitempty"`
	Reason        *SuppressionDetailReason `json:"reason,omitempty"`
	Meta          ResponseMeta             `json:"-"`
}

func (m *SuppressionDetail) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type SuppressionDetailReason string

const (
	SuppressionDetailReasonHardBounce  SuppressionDetailReason = "hard_bounce"
	SuppressionDetailReasonSoftBounce  SuppressionDetailReason = "soft_bounce"
	SuppressionDetailReasonComplaint   SuppressionDetailReason = "complaint"
	SuppressionDetailReasonManual      SuppressionDetailReason = "manual"
	SuppressionDetailReasonUnsubscribe SuppressionDetailReason = "unsubscribe"
)

var knownSuppressionDetailReason = map[SuppressionDetailReason]bool{
	SuppressionDetailReasonHardBounce:  true,
	SuppressionDetailReasonSoftBounce:  true,
	SuppressionDetailReasonComplaint:   true,
	SuppressionDetailReasonManual:      true,
	SuppressionDetailReasonUnsubscribe: true,
}

func (v SuppressionDetailReason) Known() bool {
	return knownSuppressionDetailReason[v]
}

func (v SuppressionDetailReason) String() string {
	return string(v)
}

type SuppressionListResponse struct {
	Data       []Suppression `json:"data"`
	HasMore    bool          `json:"has_more"`
	NextCursor *string       `json:"next_cursor,omitempty"`
	Meta       ResponseMeta  `json:"-"`
}

func (m *SuppressionListResponse) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type SuppressionReason string

const (
	SuppressionReasonHardBounce  SuppressionReason = "hard_bounce"
	SuppressionReasonSoftBounce  SuppressionReason = "soft_bounce"
	SuppressionReasonComplaint   SuppressionReason = "complaint"
	SuppressionReasonManual      SuppressionReason = "manual"
	SuppressionReasonUnsubscribe SuppressionReason = "unsubscribe"
)

var knownSuppressionReason = map[SuppressionReason]bool{
	SuppressionReasonHardBounce:  true,
	SuppressionReasonSoftBounce:  true,
	SuppressionReasonComplaint:   true,
	SuppressionReasonManual:      true,
	SuppressionReasonUnsubscribe: true,
}

func (v SuppressionReason) Known() bool {
	return knownSuppressionReason[v]
}

func (v SuppressionReason) String() string {
	return string(v)
}

type Tag struct {
	CreatedAt time.Time        `json:"created_at"`
	ID        string           `json:"id"`
	Name      string           `json:"name"`
	UpdatedAt time.Time        `json:"updated_at"`
	Color     Optional[string] `json:"color,omitzero"`
	Meta      ResponseMeta     `json:"-"`
}

func (m *Tag) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type TagCreate struct {
	Name  string  `json:"name"`
	Color *string `json:"color,omitempty"`
}

type TagListResponse struct {
	Data       []Tag        `json:"data"`
	HasMore    *bool        `json:"has_more,omitempty"`
	NextCursor *string      `json:"next_cursor,omitempty"`
	Meta       ResponseMeta `json:"-"`
}

func (m *TagListResponse) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type Template struct {
	CreatedAt        time.Time    `json:"created_at"`
	ID               string       `json:"id"`
	LatestVersion    int          `json:"latest_version"`
	Name             string       `json:"name"`
	UpdatedAt        time.Time    `json:"updated_at"`
	ArchivedAt       *time.Time   `json:"archived_at,omitempty"`
	PublishedVersion *int         `json:"published_version,omitempty"`
	Subject          *string      `json:"subject,omitempty"`
	Variables        []string     `json:"variables,omitempty"`
	Meta             ResponseMeta `json:"-"`
}

func (m *Template) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type TemplateCreate struct {
	Name    string  `json:"name"`
	HTML    *string `json:"html,omitempty"`
	Publish *bool   `json:"publish,omitempty"`
	Subject *string `json:"subject,omitempty"`
	Text    *string `json:"text,omitempty"`
}

type TemplateListResponse struct {
	Data       []Template   `json:"data"`
	HasMore    bool         `json:"has_more"`
	NextCursor *string      `json:"next_cursor,omitempty"`
	Meta       ResponseMeta `json:"-"`
}

func (m *TemplateListResponse) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type TemplatePublishRequest struct {
	Version int `json:"version"`
}

type TemplateRenderRequest struct {
	Data       map[string]string `json:"data,omitempty"`
	HTML       *string           `json:"html,omitempty"`
	Subject    *string           `json:"subject,omitempty"`
	TemplateID *string           `json:"template_id,omitempty"`
	Text       *string           `json:"text,omitempty"`
	Version    *int              `json:"version,omitempty"`
}

type TemplateRenderResult struct {
	HTML             *string      `json:"html,omitempty"`
	MissingVariables []string     `json:"missing_variables,omitempty"`
	Subject          *string      `json:"subject,omitempty"`
	Text             *string      `json:"text,omitempty"`
	Variables        []string     `json:"variables,omitempty"`
	Meta             ResponseMeta `json:"-"`
}

func (m *TemplateRenderResult) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type TemplateUpdate struct {
	HTML    *string `json:"html,omitempty"`
	Name    *string `json:"name,omitempty"`
	Subject *string `json:"subject,omitempty"`
	Text    *string `json:"text,omitempty"`
}

type TemplateVersion struct {
	Checksum  string       `json:"checksum"`
	CreatedAt time.Time    `json:"created_at"`
	Version   int          `json:"version"`
	HTML      *string      `json:"html,omitempty"`
	Subject   *string      `json:"subject,omitempty"`
	Text      *string      `json:"text,omitempty"`
	Variables []string     `json:"variables,omitempty"`
	Meta      ResponseMeta `json:"-"`
}

func (m *TemplateVersion) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type TemplateVersionCreate struct {
	HTML    *string `json:"html,omitempty"`
	Publish *bool   `json:"publish,omitempty"`
	Subject *string `json:"subject,omitempty"`
	Text    *string `json:"text,omitempty"`
}

type TemplateVersionListResponse struct {
	Data       []TemplateVersion `json:"data"`
	HasMore    bool              `json:"has_more"`
	NextCursor *string           `json:"next_cursor,omitempty"`
	Meta       ResponseMeta      `json:"-"`
}

func (m *TemplateVersionListResponse) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type TemplateWithContent struct {
	CreatedAt        time.Time    `json:"created_at"`
	ID               string       `json:"id"`
	LatestVersion    int          `json:"latest_version"`
	Name             string       `json:"name"`
	UpdatedAt        time.Time    `json:"updated_at"`
	ArchivedAt       *time.Time   `json:"archived_at,omitempty"`
	HTML             *string      `json:"html,omitempty"`
	PublishedVersion *int         `json:"published_version,omitempty"`
	Subject          *string      `json:"subject,omitempty"`
	Text             *string      `json:"text,omitempty"`
	Variables        []string     `json:"variables,omitempty"`
	Version          *int         `json:"version,omitempty"`
	Meta             ResponseMeta `json:"-"`
}

func (m *TemplateWithContent) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type TrackingOptions struct {
	Clicks        *bool    `json:"clicks,omitempty"`
	ClicksExclude []string `json:"clicks_exclude,omitempty"`
	Opens         *bool    `json:"opens,omitempty"`
}

type UnsubscribeContactBodyObject struct {
	Reason *string `json:"reason,omitempty"`
}

type Webhook struct {
	Active         bool                `json:"active"`
	CreatedAt      time.Time           `json:"created_at"`
	Events         []WebhookEventType  `json:"events"`
	ID             string              `json:"id"`
	URL            string              `json:"url"`
	Description    *string             `json:"description,omitempty"`
	DisabledAt     Optional[time.Time] `json:"disabled_at,omitzero"`
	DisabledReason Optional[string]    `json:"disabled_reason,omitzero"`
	DomainIds      []string            `json:"domain_ids,omitempty"`
	FailureCount   *int                `json:"failure_count,omitempty"`
	UpdatedAt      *time.Time          `json:"updated_at,omitempty"`
	Meta           ResponseMeta        `json:"-"`
}

func (m *Webhook) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type WebhookBulkReplayRequest struct {
	EventIds []string `json:"event_ids"`
}

type WebhookBulkReplayResponse struct {
	ReplayedCount int          `json:"replayed_count"`
	Meta          ResponseMeta `json:"-"`
}

func (m *WebhookBulkReplayResponse) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type WebhookCreateRequest struct {
	Events      []WebhookEventType `json:"events"`
	URL         string             `json:"url"`
	Description *string            `json:"description,omitempty"`
	DomainIds   []string           `json:"domain_ids,omitempty"`
	Secret      *string            `json:"secret,omitempty"`
}

type WebhookCreateResponse struct {
	Active      bool               `json:"active"`
	CreatedAt   time.Time          `json:"created_at"`
	Events      []WebhookEventType `json:"events"`
	ID          string             `json:"id"`
	Secret      string             `json:"secret"`
	URL         string             `json:"url"`
	Description *string            `json:"description,omitempty"`
	DomainIds   []string           `json:"domain_ids,omitempty"`
	UpdatedAt   *time.Time         `json:"updated_at,omitempty"`
	Meta        ResponseMeta       `json:"-"`
}

func (m *WebhookCreateResponse) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type WebhookDeliveryLog struct {
	Attempt           int                      `json:"attempt"`
	CreatedAt         time.Time                `json:"created_at"`
	EventID           string                   `json:"event_id"`
	EventType         string                   `json:"event_type"`
	ID                string                   `json:"id"`
	Status            WebhookDeliveryLogStatus `json:"status"`
	WebhookEndpointID string                   `json:"webhook_endpoint_id"`
	DeliveredAt       Optional[time.Time]      `json:"delivered_at,omitzero"`
	NextRetryAt       Optional[time.Time]      `json:"next_retry_at,omitzero"`
	Payload           json.RawMessage          `json:"payload,omitempty"`
	ResponseBody      Optional[string]         `json:"response_body,omitzero"`
	ResponseCode      Optional[int]            `json:"response_code,omitzero"`
	Meta              ResponseMeta             `json:"-"`
}

func (m *WebhookDeliveryLog) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type WebhookDeliveryLogListResponse struct {
	Data       []WebhookDeliveryLog `json:"data"`
	HasMore    bool                 `json:"has_more"`
	NextCursor *string              `json:"next_cursor,omitempty"`
	Meta       ResponseMeta         `json:"-"`
}

func (m *WebhookDeliveryLogListResponse) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type WebhookDeliveryLogStatus string

const (
	WebhookDeliveryLogStatusPending WebhookDeliveryLogStatus = "pending"
	WebhookDeliveryLogStatusSuccess WebhookDeliveryLogStatus = "success"
	WebhookDeliveryLogStatusFailed  WebhookDeliveryLogStatus = "failed"
)

var knownWebhookDeliveryLogStatus = map[WebhookDeliveryLogStatus]bool{
	WebhookDeliveryLogStatusPending: true,
	WebhookDeliveryLogStatusSuccess: true,
	WebhookDeliveryLogStatusFailed:  true,
}

func (v WebhookDeliveryLogStatus) Known() bool {
	return knownWebhookDeliveryLogStatus[v]
}

func (v WebhookDeliveryLogStatus) String() string {
	return string(v)
}

type WebhookEventType string

const (
	WebhookEventTypeEmailSent                        WebhookEventType = "email.sent"
	WebhookEventTypeEmailDelivered                   WebhookEventType = "email.delivered"
	WebhookEventTypeEmailBounced                     WebhookEventType = "email.bounced"
	WebhookEventTypeEmailOpened                      WebhookEventType = "email.opened"
	WebhookEventTypeEmailClicked                     WebhookEventType = "email.clicked"
	WebhookEventTypeEmailComplained                  WebhookEventType = "email.complained"
	WebhookEventTypeEmailFailed                      WebhookEventType = "email.failed"
	WebhookEventTypeEmailDelayed                     WebhookEventType = "email.delayed"
	WebhookEventTypeEmailCancelled                   WebhookEventType = "email.cancelled"
	WebhookEventTypeEmailReceived                    WebhookEventType = "email.received"
	WebhookEventTypeDomainVerified                   WebhookEventType = "domain.verified"
	WebhookEventTypeDomainVerificationFailed         WebhookEventType = "domain.verification_failed"
	WebhookEventTypeTrackingDomainVerified           WebhookEventType = "tracking_domain.verified"
	WebhookEventTypeTrackingDomainVerificationFailed WebhookEventType = "tracking_domain.verification_failed"
	WebhookEventTypeCampaignStarted                  WebhookEventType = "campaign.started"
	WebhookEventTypeCampaignPaused                   WebhookEventType = "campaign.paused"
	WebhookEventTypeCampaignResumed                  WebhookEventType = "campaign.resumed"
	WebhookEventTypeCampaignCompleted                WebhookEventType = "campaign.completed"
	WebhookEventTypeCampaignCancelled                WebhookEventType = "campaign.cancelled"
	WebhookEventTypeCampaignAutoPaused               WebhookEventType = "campaign.auto_paused"
	WebhookEventTypeContactStatusChanged             WebhookEventType = "contact.status_changed"
	WebhookEventTypeContactImportCompleted           WebhookEventType = "contact.import_completed"
	WebhookEventTypeSuppressionCreated               WebhookEventType = "suppression.created"
	WebhookEventTypeSuppressionRemoved               WebhookEventType = "suppression.removed"
)

var knownWebhookEventType = map[WebhookEventType]bool{
	WebhookEventTypeEmailSent:                        true,
	WebhookEventTypeEmailDelivered:                   true,
	WebhookEventTypeEmailBounced:                     true,
	WebhookEventTypeEmailOpened:                      true,
	WebhookEventTypeEmailClicked:                     true,
	WebhookEventTypeEmailComplained:                  true,
	WebhookEventTypeEmailFailed:                      true,
	WebhookEventTypeEmailDelayed:                     true,
	WebhookEventTypeEmailCancelled:                   true,
	WebhookEventTypeEmailReceived:                    true,
	WebhookEventTypeDomainVerified:                   true,
	WebhookEventTypeDomainVerificationFailed:         true,
	WebhookEventTypeTrackingDomainVerified:           true,
	WebhookEventTypeTrackingDomainVerificationFailed: true,
	WebhookEventTypeCampaignStarted:                  true,
	WebhookEventTypeCampaignPaused:                   true,
	WebhookEventTypeCampaignResumed:                  true,
	WebhookEventTypeCampaignCompleted:                true,
	WebhookEventTypeCampaignCancelled:                true,
	WebhookEventTypeCampaignAutoPaused:               true,
	WebhookEventTypeContactStatusChanged:             true,
	WebhookEventTypeContactImportCompleted:           true,
	WebhookEventTypeSuppressionCreated:               true,
	WebhookEventTypeSuppressionRemoved:               true,
}

func (v WebhookEventType) Known() bool {
	return knownWebhookEventType[v]
}

func (v WebhookEventType) String() string {
	return string(v)
}

type WebhookListResponse struct {
	Data       []Webhook    `json:"data"`
	HasMore    bool         `json:"has_more"`
	NextCursor *string      `json:"next_cursor,omitempty"`
	Meta       ResponseMeta `json:"-"`
}

func (m *WebhookListResponse) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type WebhookRotateSecretResponse struct {
	PreviousSecretExpiresAt time.Time    `json:"previous_secret_expires_at"`
	Secret                  string       `json:"secret"`
	Meta                    ResponseMeta `json:"-"`
}

func (m *WebhookRotateSecretResponse) setMeta(meta ResponseMeta) {
	m.Meta = meta
}

type WebhookUpdateRequest struct {
	Active      *bool              `json:"active,omitempty"`
	Description *string            `json:"description,omitempty"`
	DomainIds   []string           `json:"domain_ids,omitempty"`
	Events      []WebhookEventType `json:"events,omitempty"`
	URL         *string            `json:"url,omitempty"`
}
