// Code generated by epostix-codegen. DO NOT EDIT.

package epostix

type resources struct {
	Analytics    *AnalyticsResource
	APIKeys      *APIKeysResource
	Attachments  *AttachmentsResource
	Broadcasts   *BroadcastsResource
	Contacts     *ContactsResource
	Domains      *DomainsResource
	Emails       *EmailsResource
	Events       *EventsResource
	Inbound      *InboundResource
	Suppressions *SuppressionsResource
	Tags         *TagsResource
	Templates    *TemplatesResource
	Webhooks     *WebhooksResource
}

func (r *TemplatesResource) attachChildren(client *Client) {
	r.Versions = &TemplatesVersionsResource{client: client}
}

func (r *WebhooksResource) attachChildren(client *Client) {
	r.Logs = &WebhooksLogsResource{client: client}
}

func buildResources(client *Client) resources {
	built := resources{
		Analytics:    &AnalyticsResource{client: client},
		APIKeys:      &APIKeysResource{client: client},
		Attachments:  &AttachmentsResource{client: client},
		Broadcasts:   &BroadcastsResource{client: client},
		Contacts:     &ContactsResource{client: client},
		Domains:      &DomainsResource{client: client},
		Emails:       &EmailsResource{client: client},
		Events:       &EventsResource{client: client},
		Inbound:      &InboundResource{client: client},
		Suppressions: &SuppressionsResource{client: client},
		Tags:         &TagsResource{client: client},
		Templates:    &TemplatesResource{client: client},
		Webhooks:     &WebhooksResource{client: client},
	}

	built.Templates.attachChildren(client)
	built.Webhooks.attachChildren(client)

	return built
}
