// Code generated by epostix-codegen. DO NOT EDIT.

package epostix

import (
	"context"
	"net/url"
	"time"
)

var _ = time.Time{}
var _ = url.Values{}

type SuppressionsResource struct {
	client *Client
}

type ListSuppressionsParams struct {
	Limit         *int
	StartingAfter *string
	EndingBefore  *string
	Reason        *ListSuppressionsReason
	Email         *string
	CreatedAfter  *time.Time
	CreatedBefore *time.Time
}

func (p *ListSuppressionsParams) values() url.Values {
	out := url.Values{}
	if p == nil {
		return out
	}

	if p.Limit != nil {
		out.Set("limit", formatQueryValue(*p.Limit))
	}
	if p.StartingAfter != nil {
		out.Set("starting_after", formatQueryValue(*p.StartingAfter))
	}
	if p.EndingBefore != nil {
		out.Set("ending_before", formatQueryValue(*p.EndingBefore))
	}
	if p.Reason != nil {
		out.Set("reason", formatQueryValue(*p.Reason))
	}
	if p.Email != nil {
		out.Set("email", formatQueryValue(*p.Email))
	}
	if p.CreatedAfter != nil {
		out.Set("created_after", formatQueryValue(*p.CreatedAfter))
	}
	if p.CreatedBefore != nil {
		out.Set("created_before", formatQueryValue(*p.CreatedBefore))
	}

	return out
}

func (r *SuppressionsResource) BulkCreateSuppressions(ctx context.Context, body *BulkSuppressionCreate, opts ...RequestOption) (*BulkSuppressionResponse, error) {
	req := &requestInput{
		op:   operations.BulkCreateSuppressions,
		body: body,
	}

	return execute[BulkSuppressionResponse](ctx, r.client, req, opts...)
}

func (r *SuppressionsResource) CreateSuppression(ctx context.Context, body *SuppressionCreate, opts ...RequestOption) (*Suppression, error) {
	req := &requestInput{
		op:   operations.CreateSuppression,
		body: body,
	}

	return execute[Suppression](ctx, r.client, req, opts...)
}

func (r *SuppressionsResource) DeleteSuppression(ctx context.Context, email string, opts ...RequestOption) error {
	req := &requestInput{
		op:   operations.DeleteSuppression,
		path: []string{email},
	}

	_, err := execute[struct{}](ctx, r.client, req, opts...)
	return err
}

func (r *SuppressionsResource) GetSuppression(ctx context.Context, email string, opts ...RequestOption) (*SuppressionDetail, error) {
	req := &requestInput{
		op:   operations.GetSuppression,
		path: []string{email},
	}

	return execute[SuppressionDetail](ctx, r.client, req, opts...)
}

func (r *SuppressionsResource) ListSuppressions(ctx context.Context, params *ListSuppressionsParams, opts ...RequestOption) (*SuppressionListResponse, error) {
	req := &requestInput{
		op:    operations.ListSuppressions,
		query: params.values(),
	}

	return execute[SuppressionListResponse](ctx, r.client, req, opts...)
}

func (r *SuppressionsResource) ListSuppressionsIterator(ctx context.Context, params *ListSuppressionsParams, opts ...RequestOption) *Iterator[Suppression] {
	return newIterator[Suppression](ctx, r.client, &paginateInput{
		op:          operations.ListSuppressions,
		query:       params.values(),
		cursorParam: "starting_after",
	}, opts...)
}
