// Code generated by epostix-codegen. DO NOT EDIT.

package epostix

import (
	"context"
	"net/url"
	"time"
)

var _ = time.Time{}
var _ = url.Values{}

type TagsResource struct {
	client *Client
}

type ListTagsParams struct {
	Limit         *int
	StartingAfter *string
	EndingBefore  *string
}

func (p *ListTagsParams) values() url.Values {
	out := url.Values{}
	if p == nil {
		return out
	}

	if p.Limit != nil {
		out.Set("limit", formatQueryValue(*p.Limit))
	}
	if p.StartingAfter != nil {
		out.Set("starting_after", formatQueryValue(*p.StartingAfter))
	}
	if p.EndingBefore != nil {
		out.Set("ending_before", formatQueryValue(*p.EndingBefore))
	}

	return out
}

func (r *TagsResource) CreateTag(ctx context.Context, body *TagCreate, opts ...RequestOption) (*Tag, error) {
	req := &requestInput{
		op:   operations.CreateTag,
		body: body,
	}

	return execute[Tag](ctx, r.client, req, opts...)
}

func (r *TagsResource) DeleteTag(ctx context.Context, tagID string, opts ...RequestOption) error {
	req := &requestInput{
		op:   operations.DeleteTag,
		path: []string{tagID},
	}

	_, err := execute[struct{}](ctx, r.client, req, opts...)
	return err
}

func (r *TagsResource) ListTags(ctx context.Context, params *ListTagsParams, opts ...RequestOption) (*TagListResponse, error) {
	req := &requestInput{
		op:    operations.ListTags,
		query: params.values(),
	}

	return execute[TagListResponse](ctx, r.client, req, opts...)
}

func (r *TagsResource) ListTagsIterator(ctx context.Context, params *ListTagsParams, opts ...RequestOption) *Iterator[Tag] {
	return newIterator[Tag](ctx, r.client, &paginateInput{
		op:          operations.ListTags,
		query:       params.values(),
		cursorParam: "starting_after",
	}, opts...)
}
