// Code generated by epostix-codegen. DO NOT EDIT.

package epostix

import (
	"context"
	"net/url"
	"time"
)

var _ = time.Time{}
var _ = url.Values{}

type TemplatesVersionsResource struct {
	client *Client
}

type ListTemplateVersionsParams struct {
	Limit         *int
	StartingAfter *string
}

func (p *ListTemplateVersionsParams) values() url.Values {
	out := url.Values{}
	if p == nil {
		return out
	}

	if p.Limit != nil {
		out.Set("limit", formatQueryValue(*p.Limit))
	}
	if p.StartingAfter != nil {
		out.Set("starting_after", formatQueryValue(*p.StartingAfter))
	}

	return out
}

func (r *TemplatesVersionsResource) CreateTemplateVersion(ctx context.Context, templateID string, body *TemplateVersionCreate, opts ...RequestOption) (*TemplateVersion, error) {
	req := &requestInput{
		op:   operations.CreateTemplateVersion,
		path: []string{templateID},
		body: body,
	}

	return execute[TemplateVersion](ctx, r.client, req, opts...)
}

func (r *TemplatesVersionsResource) GetTemplateVersion(ctx context.Context, templateID string, version string, opts ...RequestOption) (*TemplateVersion, error) {
	req := &requestInput{
		op:   operations.GetTemplateVersion,
		path: []string{templateID, version},
	}

	return execute[TemplateVersion](ctx, r.client, req, opts...)
}

func (r *TemplatesVersionsResource) ListTemplateVersions(ctx context.Context, templateID string, params *ListTemplateVersionsParams, opts ...RequestOption) (*TemplateVersionListResponse, error) {
	req := &requestInput{
		op:    operations.ListTemplateVersions,
		path:  []string{templateID},
		query: params.values(),
	}

	return execute[TemplateVersionListResponse](ctx, r.client, req, opts...)
}

func (r *TemplatesVersionsResource) ListTemplateVersionsIterator(ctx context.Context, templateID string, params *ListTemplateVersionsParams, opts ...RequestOption) *Iterator[TemplateVersion] {
	return newIterator[TemplateVersion](ctx, r.client, &paginateInput{
		op:          operations.ListTemplateVersions,
		path:        []string{templateID},
		query:       params.values(),
		cursorParam: "starting_after",
	}, opts...)
}

func (r *TemplatesVersionsResource) PublishTemplateVersion(ctx context.Context, templateID string, body *TemplatePublishRequest, opts ...RequestOption) (*Template, error) {
	req := &requestInput{
		op:   operations.PublishTemplateVersion,
		path: []string{templateID},
		body: body,
	}

	return execute[Template](ctx, r.client, req, opts...)
}
