// Code generated by epostix-codegen. DO NOT EDIT.

package epostix

import (
	"context"
	"net/url"
	"time"
)

var _ = time.Time{}
var _ = url.Values{}

type TemplatesResource struct {
	client   *Client
	Versions *TemplatesVersionsResource
}

type GetTemplateParams struct {
	Version *int
}

func (p *GetTemplateParams) values() url.Values {
	out := url.Values{}
	if p == nil {
		return out
	}

	if p.Version != nil {
		out.Set("version", formatQueryValue(*p.Version))
	}

	return out
}

type ListTemplatesParams struct {
	Limit         *int
	StartingAfter *string
	EndingBefore  *string
}

func (p *ListTemplatesParams) values() url.Values {
	out := url.Values{}
	if p == nil {
		return out
	}

	if p.Limit != nil {
		out.Set("limit", formatQueryValue(*p.Limit))
	}
	if p.StartingAfter != nil {
		out.Set("starting_after", formatQueryValue(*p.StartingAfter))
	}
	if p.EndingBefore != nil {
		out.Set("ending_before", formatQueryValue(*p.EndingBefore))
	}

	return out
}

func (r *TemplatesResource) CreateTemplate(ctx context.Context, body *TemplateCreate, opts ...RequestOption) (*Template, error) {
	req := &requestInput{
		op:   operations.CreateTemplate,
		body: body,
	}

	return execute[Template](ctx, r.client, req, opts...)
}

func (r *TemplatesResource) DeleteTemplate(ctx context.Context, templateID string, opts ...RequestOption) error {
	req := &requestInput{
		op:   operations.DeleteTemplate,
		path: []string{templateID},
	}

	_, err := execute[struct{}](ctx, r.client, req, opts...)
	return err
}

func (r *TemplatesResource) GetTemplate(ctx context.Context, templateID string, params *GetTemplateParams, opts ...RequestOption) (*TemplateWithContent, error) {
	req := &requestInput{
		op:    operations.GetTemplate,
		path:  []string{templateID},
		query: params.values(),
	}

	return execute[TemplateWithContent](ctx, r.client, req, opts...)
}

func (r *TemplatesResource) ListTemplates(ctx context.Context, params *ListTemplatesParams, opts ...RequestOption) (*TemplateListResponse, error) {
	req := &requestInput{
		op:    operations.ListTemplates,
		query: params.values(),
	}

	return execute[TemplateListResponse](ctx, r.client, req, opts...)
}

func (r *TemplatesResource) ListTemplatesIterator(ctx context.Context, params *ListTemplatesParams, opts ...RequestOption) *Iterator[Template] {
	return newIterator[Template](ctx, r.client, &paginateInput{
		op:          operations.ListTemplates,
		query:       params.values(),
		cursorParam: "starting_after",
	}, opts...)
}

func (r *TemplatesResource) RenderTemplate(ctx context.Context, body *TemplateRenderRequest, opts ...RequestOption) (*TemplateRenderResult, error) {
	req := &requestInput{
		op:   operations.RenderTemplate,
		body: body,
	}

	return execute[TemplateRenderResult](ctx, r.client, req, opts...)
}

func (r *TemplatesResource) UpdateTemplate(ctx context.Context, templateID string, body *TemplateUpdate, opts ...RequestOption) (*TemplateWithContent, error) {
	req := &requestInput{
		op:   operations.UpdateTemplate,
		path: []string{templateID},
		body: body,
	}

	return execute[TemplateWithContent](ctx, r.client, req, opts...)
}
