// Code generated by epostix-codegen. DO NOT EDIT.

package epostix

import (
	"encoding/json"
	"fmt"
)

func decodeEmailCreateAttachmentsItem(raw json.RawMessage) (EmailCreateAttachmentsItem, error) {
	var probe map[string]json.RawMessage
	if err := json.Unmarshal(raw, &probe); err != nil {
		return nil, fmt.Errorf("decode EmailCreateAttachmentsItem: %w", err)
	}

	if _, ok := probe["content"]; ok {
		var value Attachment
		if err := json.Unmarshal(raw, &value); err != nil {
			return nil, fmt.Errorf("decode Attachment: %w", err)
		}
		return value, nil
	}

	if _, ok := probe["content_url"]; ok {
		var value AttachmentURL
		if err := json.Unmarshal(raw, &value); err != nil {
			return nil, fmt.Errorf("decode AttachmentURL: %w", err)
		}
		return value, nil
	}

	if _, ok := probe["attachment_id"]; ok {
		var value AttachmentRef
		if err := json.Unmarshal(raw, &value); err != nil {
			return nil, fmt.Errorf("decode AttachmentRef: %w", err)
		}
		return value, nil
	}

	return nil, fmt.Errorf("the server returned a EmailCreateAttachmentsItem shape this version does not recognise")
}

func decodeEmailCreateAttachmentsItemSlice(raw json.RawMessage) ([]EmailCreateAttachmentsItem, error) {
	var items []json.RawMessage
	if err := json.Unmarshal(raw, &items); err != nil {
		return nil, fmt.Errorf("decode EmailCreateAttachmentsItem list: %w", err)
	}

	out := make([]EmailCreateAttachmentsItem, 0, len(items))
	for _, item := range items {
		value, err := decodeEmailCreateAttachmentsItem(item)
		if err != nil {
			return nil, err
		}
		out = append(out, value)
	}

	return out, nil
}
