// Code generated by epostix-codegen. DO NOT EDIT.

package epostix

import (
	"context"
	"net/url"
	"time"
)

var _ = time.Time{}
var _ = url.Values{}

type WebhooksResource struct {
	client *Client
	Logs   *WebhooksLogsResource
}

type ListWebhooksParams struct {
	Limit         *int
	StartingAfter *string
	EndingBefore  *string
}

func (p *ListWebhooksParams) values() url.Values {
	out := url.Values{}
	if p == nil {
		return out
	}

	if p.Limit != nil {
		out.Set("limit", formatQueryValue(*p.Limit))
	}
	if p.StartingAfter != nil {
		out.Set("starting_after", formatQueryValue(*p.StartingAfter))
	}
	if p.EndingBefore != nil {
		out.Set("ending_before", formatQueryValue(*p.EndingBefore))
	}

	return out
}

func (r *WebhooksResource) CreateWebhook(ctx context.Context, body *WebhookCreateRequest, opts ...RequestOption) (*WebhookCreateResponse, error) {
	req := &requestInput{
		op:   operations.CreateWebhook,
		body: body,
	}

	return execute[WebhookCreateResponse](ctx, r.client, req, opts...)
}

func (r *WebhooksResource) DeleteWebhook(ctx context.Context, webhookID string, opts ...RequestOption) error {
	req := &requestInput{
		op:   operations.DeleteWebhook,
		path: []string{webhookID},
	}

	_, err := execute[struct{}](ctx, r.client, req, opts...)
	return err
}

func (r *WebhooksResource) GetWebhook(ctx context.Context, webhookID string, opts ...RequestOption) (*Webhook, error) {
	req := &requestInput{
		op:   operations.GetWebhook,
		path: []string{webhookID},
	}

	return execute[Webhook](ctx, r.client, req, opts...)
}

func (r *WebhooksResource) ListWebhooks(ctx context.Context, params *ListWebhooksParams, opts ...RequestOption) (*WebhookListResponse, error) {
	req := &requestInput{
		op:    operations.ListWebhooks,
		query: params.values(),
	}

	return execute[WebhookListResponse](ctx, r.client, req, opts...)
}

func (r *WebhooksResource) ListWebhooksIterator(ctx context.Context, params *ListWebhooksParams, opts ...RequestOption) *Iterator[Webhook] {
	return newIterator[Webhook](ctx, r.client, &paginateInput{
		op:          operations.ListWebhooks,
		query:       params.values(),
		cursorParam: "starting_after",
	}, opts...)
}

func (r *WebhooksResource) RotateWebhookSecret(ctx context.Context, webhookID string, opts ...RequestOption) (*WebhookRotateSecretResponse, error) {
	req := &requestInput{
		op:   operations.RotateWebhookSecret,
		path: []string{webhookID},
	}

	return execute[WebhookRotateSecretResponse](ctx, r.client, req, opts...)
}

func (r *WebhooksResource) TestWebhook(ctx context.Context, webhookID string, opts ...RequestOption) (*WebhookDeliveryLog, error) {
	req := &requestInput{
		op:   operations.TestWebhook,
		path: []string{webhookID},
	}

	return execute[WebhookDeliveryLog](ctx, r.client, req, opts...)
}

func (r *WebhooksResource) ToggleWebhook(ctx context.Context, webhookID string, opts ...RequestOption) (*Webhook, error) {
	req := &requestInput{
		op:   operations.ToggleWebhook,
		path: []string{webhookID},
	}

	return execute[Webhook](ctx, r.client, req, opts...)
}

func (r *WebhooksResource) UpdateWebhook(ctx context.Context, webhookID string, body *WebhookUpdateRequest, opts ...RequestOption) (*Webhook, error) {
	req := &requestInput{
		op:   operations.UpdateWebhook,
		path: []string{webhookID},
		body: body,
	}

	return execute[Webhook](ctx, r.client, req, opts...)
}
