// Code generated by epostix-codegen. DO NOT EDIT.

package epostix

import (
	"context"
	"net/url"
	"time"
)

var _ = time.Time{}
var _ = url.Values{}

type WebhooksLogsResource struct {
	client *Client
}

type ListWebhookLogsParams struct {
	Limit         *int
	StartingAfter *string
	EndingBefore  *string
	EventType     *string
	Status        *ListWebhookLogsStatus
	CreatedAfter  *time.Time
	CreatedBefore *time.Time
}

func (p *ListWebhookLogsParams) values() url.Values {
	out := url.Values{}
	if p == nil {
		return out
	}

	if p.Limit != nil {
		out.Set("limit", formatQueryValue(*p.Limit))
	}
	if p.StartingAfter != nil {
		out.Set("starting_after", formatQueryValue(*p.StartingAfter))
	}
	if p.EndingBefore != nil {
		out.Set("ending_before", formatQueryValue(*p.EndingBefore))
	}
	if p.EventType != nil {
		out.Set("event_type", formatQueryValue(*p.EventType))
	}
	if p.Status != nil {
		out.Set("status", formatQueryValue(*p.Status))
	}
	if p.CreatedAfter != nil {
		out.Set("created_after", formatQueryValue(*p.CreatedAfter))
	}
	if p.CreatedBefore != nil {
		out.Set("created_before", formatQueryValue(*p.CreatedBefore))
	}

	return out
}

func (r *WebhooksLogsResource) BulkReplayWebhook(ctx context.Context, webhookID string, body *WebhookBulkReplayRequest, opts ...RequestOption) (*WebhookBulkReplayResponse, error) {
	req := &requestInput{
		op:   operations.BulkReplayWebhook,
		path: []string{webhookID},
		body: body,
	}

	return execute[WebhookBulkReplayResponse](ctx, r.client, req, opts...)
}

func (r *WebhooksLogsResource) ListWebhookLogs(ctx context.Context, webhookID string, params *ListWebhookLogsParams, opts ...RequestOption) (*WebhookDeliveryLogListResponse, error) {
	req := &requestInput{
		op:    operations.ListWebhookLogs,
		path:  []string{webhookID},
		query: params.values(),
	}

	return execute[WebhookDeliveryLogListResponse](ctx, r.client, req, opts...)
}

func (r *WebhooksLogsResource) ListWebhookLogsIterator(ctx context.Context, webhookID string, params *ListWebhookLogsParams, opts ...RequestOption) *Iterator[WebhookDeliveryLog] {
	return newIterator[WebhookDeliveryLog](ctx, r.client, &paginateInput{
		op:          operations.ListWebhookLogs,
		path:        []string{webhookID},
		query:       params.values(),
		cursorParam: "starting_after",
	}, opts...)
}

func (r *WebhooksLogsResource) ReplayWebhookLog(ctx context.Context, webhookID string, logID string, opts ...RequestOption) (*WebhookDeliveryLog, error) {
	req := &requestInput{
		op:   operations.ReplayWebhookLog,
		path: []string{webhookID, logID},
	}

	return execute[WebhookDeliveryLog](ctx, r.client, req, opts...)
}
